// Initialise the global array that allows the lookup of the depth of a given object
// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
// NOTE: MacroExpansion is used to insert the array initialisation at import time
gml_pragma( "global", "__global_object_depths()");

// insert the generated arrays here
global.__objectDepths[0] = -9000000; // oTestKeys
global.__objectDepths[1] = -50000; // oNumberOverlayFade
global.__objectDepths[2] = -500000; // oPlayback
global.__objectDepths[3] = -500000; // oRecord
global.__objectDepths[4] = -5; // oSolid1
global.__objectDepths[5] = -2; // oSlope1
global.__objectDepths[6] = -2; // oSlope2
global.__objectDepths[7] = -2; // oSlope3
global.__objectDepths[8] = -2; // oSlope4
global.__objectDepths[9] = -2; // oSlope1B
global.__objectDepths[10] = -2; // oSlope2B
global.__objectDepths[11] = -2; // oSlope3B
global.__objectDepths[12] = -2; // oSlope4B
global.__objectDepths[13] = -2; // oSlopeFL1
global.__objectDepths[14] = -2; // oSlopeFL2
global.__objectDepths[15] = -2; // oSlopeFL1B
global.__objectDepths[16] = -2; // oSlopeFL2B
global.__objectDepths[17] = -5; // oSolid2x1
global.__objectDepths[18] = -5; // oSolid1x2
global.__objectDepths[19] = -5; // oSolid4x1
global.__objectDepths[20] = -5; // oSolid1x4
global.__objectDepths[21] = -5; // oSolid8x1
global.__objectDepths[22] = -5; // oSolid1x8
global.__objectDepths[23] = -5; // oSolid2x2
global.__objectDepths[24] = -5; // oSolidItem
global.__objectDepths[25] = -100; // oBlockShoot
global.__objectDepths[26] = -100; // oBlockShootChain
global.__objectDepths[27] = -100; // oBlockBomb
global.__objectDepths[28] = -100; // oBlockBombChain
global.__objectDepths[29] = -100; // oBlockBombItem
global.__objectDepths[30] = -100; // oBlockScrew
global.__objectDepths[31] = -100; // oBlockPBomb
global.__objectDepths[32] = -100; // oBlockPBombChain
global.__objectDepths[33] = -100; // oBlockMissile
global.__objectDepths[34] = -100; // oBlockSMissile
global.__objectDepths[35] = -100; // oBlockSpeed
global.__objectDepths[36] = -101; // oBlockSand
global.__objectDepths[37] = -100; // oBlockStep
global.__objectDepths[38] = 2; // oDestroyedBlock
global.__objectDepths[39] = 100; // oMoverUp
global.__objectDepths[40] = 100; // oMoverDown
global.__objectDepths[41] = 100; // oMoverLeft
global.__objectDepths[42] = 100; // oMoverLeftUp
global.__objectDepths[43] = 100; // oMoverRight
global.__objectDepths[44] = 0; // oSpikeSolid
global.__objectDepths[45] = -5; // oSolid1Normal
global.__objectDepths[46] = -5; // oSolid2x1Normal
global.__objectDepths[47] = -5; // oSolid4x1Normal
global.__objectDepths[48] = -5; // oSolid8x1Normal
global.__objectDepths[49] = -2; // oSlope1Normal
global.__objectDepths[50] = -2; // oSlope2Normal
global.__objectDepths[51] = -2; // oSlope1BNormal
global.__objectDepths[52] = -2; // oSlope2BNormal
global.__objectDepths[53] = -5; // oSolid2x2Normal
global.__objectDepths[54] = -5; // oSolid1Rock
global.__objectDepths[55] = -5; // oSolid2x1Rock
global.__objectDepths[56] = -5; // oSolid4x1Rock
global.__objectDepths[57] = -5; // oSolid8x1Rock
global.__objectDepths[58] = -2; // oSlope1Rock
global.__objectDepths[59] = -2; // oSlope2Rock
global.__objectDepths[60] = -2; // oSlope1BRock
global.__objectDepths[61] = -2; // oSlope2BRock
global.__objectDepths[62] = -5; // oSolid2x2Rock
global.__objectDepths[63] = -5; // oSolid1Grass
global.__objectDepths[64] = -5; // oSolid2x1Grass
global.__objectDepths[65] = -5; // oSolid4x1Grass
global.__objectDepths[66] = -5; // oSolid8x1Grass
global.__objectDepths[67] = -2; // oSlope1Grass
global.__objectDepths[68] = -2; // oSlope2Grass
global.__objectDepths[69] = -2; // oSlope1BGrass
global.__objectDepths[70] = -2; // oSlope2BGrass
global.__objectDepths[71] = -5; // oSolid2x2Grass
global.__objectDepths[72] = -5; // oSolid1Stone
global.__objectDepths[73] = -5; // oSolid2x1Stone
global.__objectDepths[74] = -5; // oSolid4x1Stone
global.__objectDepths[75] = -5; // oSolid8x1Stone
global.__objectDepths[76] = -2; // oSlope1Stone
global.__objectDepths[77] = -2; // oSlope2Stone
global.__objectDepths[78] = -2; // oSlope1BStone
global.__objectDepths[79] = -2; // oSlope2BStone
global.__objectDepths[80] = -5; // oSolid2x2Stone
global.__objectDepths[81] = -5; // oSolid1Metal
global.__objectDepths[82] = -5; // oSolid2x1Metal
global.__objectDepths[83] = -5; // oSolid4x1Metal
global.__objectDepths[84] = -5; // oSolid8x1Metal
global.__objectDepths[85] = -2; // oSlope1Metal
global.__objectDepths[86] = -2; // oSlope2Metal
global.__objectDepths[87] = -2; // oSlope1BMetal
global.__objectDepths[88] = -2; // oSlope2BMetal
global.__objectDepths[89] = -5; // oSolid2x2Metal
global.__objectDepths[90] = -5; // oSolid1Wet
global.__objectDepths[91] = -5; // oSolid2x1Wet
global.__objectDepths[92] = -5; // oSolid4x1Wet
global.__objectDepths[93] = -5; // oSolid8x1Wet
global.__objectDepths[94] = -2; // oSlope1Wet
global.__objectDepths[95] = -2; // oSlope2Wet
global.__objectDepths[96] = -2; // oSlope1BWet
global.__objectDepths[97] = -2; // oSlope2BWet
global.__objectDepths[98] = -5; // oSolid2x2Wet
global.__objectDepths[99] = 5; // oPlatform1
global.__objectDepths[100] = -90; // oSaveStation
global.__objectDepths[101] = -110; // oSaveStation2
global.__objectDepths[102] = -90; // oElevator
global.__objectDepths[103] = -250; // oGFElevator
global.__objectDepths[104] = 0; // oGFElevatorFX
global.__objectDepths[105] = -100; // oSaveShip
global.__objectDepths[106] = 20; // oDecoration
global.__objectDepths[107] = -90; // oMEgg2A
global.__objectDepths[108] = -156; // oShip1
global.__objectDepths[109] = -156; // oShipOutro
global.__objectDepths[110] = -5000000; // oFinalFadeout
global.__objectDepths[111] = -100; // oA1MovingPlatform
global.__objectDepths[112] = 100; // oA1MovingPlatformBG
global.__objectDepths[113] = 0; // oClawOrb
global.__objectDepths[114] = 0; // oClawPuzzle
global.__objectDepths[115] = 0; // oClawOrbFirst
global.__objectDepths[116] = -100; // oA1MovingPlatform2
global.__objectDepths[117] = -101; // oA2BigTurbine
global.__objectDepths[118] = -101; // oA2SmallTurbine
global.__objectDepths[119] = 5; // oCurrentBubble
global.__objectDepths[120] = 0; // oBubbleSpawner
global.__objectDepths[121] = -101; // oA2WaterJetMachine
global.__objectDepths[122] = -100; // oA2WJValve
global.__objectDepths[123] = 0; // oA2WJStop
global.__objectDepths[124] = -50; // oA2WaterSpawner
global.__objectDepths[125] = 10; // oA2WJWaterA
global.__objectDepths[126] = 5; // oA2WJWaterC
global.__objectDepths[127] = 5; // oA2WJWaterA2
global.__objectDepths[128] = 105; // oA2WaterStream
global.__objectDepths[129] = 0; // oMovingPlatform1
global.__objectDepths[130] = -150; // oMachine1Core
global.__objectDepths[131] = -90; // oMachine1Beam
global.__objectDepths[132] = -100; // oMovingPlatform2
global.__objectDepths[133] = -100; // oMovingPlatform2B
global.__objectDepths[134] = -100; // oMovingPlatform2C
global.__objectDepths[135] = 0; // oGlowPlant1
global.__objectDepths[136] = 0; // oGlowPlant2
global.__objectDepths[137] = 0; // oGlowPlant3
global.__objectDepths[138] = 0; // oGlowPlant4
global.__objectDepths[139] = 0; // oA3AssemblyControl
global.__objectDepths[140] = -3; // oAutoadPlayer
global.__objectDepths[141] = -500; // oAutoadCamera
global.__objectDepths[142] = 10; // oAutoadControlTrigger
global.__objectDepths[143] = -10; // oAutoadMissile
global.__objectDepths[144] = 0; // oDrillTrigger1
global.__objectDepths[145] = 0; // oDrillSeq1
global.__objectDepths[146] = 0; // oDrillTrigger2
global.__objectDepths[147] = 0; // oDrillSeq2
global.__objectDepths[148] = 10; // oDrillBack
global.__objectDepths[149] = -99; // oDrillFront
global.__objectDepths[150] = -110; // oDrillWall
global.__objectDepths[151] = -120; // oGreenCrystal
global.__objectDepths[152] = 40; // oA3LabLight
global.__objectDepths[153] = -90; // oA3LabDoor
global.__objectDepths[154] = -110; // oLightBug
global.__objectDepths[155] = -120; // oGreenCrystalShard
global.__objectDepths[156] = 0; // oLabEntranceControl
global.__objectDepths[157] = 0; // oArea4PowerSwitch
global.__objectDepths[158] = -200; // oA4TileLight1
global.__objectDepths[159] = -200; // oA4TileLight2
global.__objectDepths[160] = -200; // oA4TileLight3
global.__objectDepths[161] = -200; // oA4TileLight4
global.__objectDepths[162] = -200; // oA4TileLight5
global.__objectDepths[163] = 100; // oA4PowerCell
global.__objectDepths[164] = -10000; // oA4EscapeSeqFX
global.__objectDepths[165] = -90; // oA4BlastDoor
global.__objectDepths[166] = 0; // oA4B14Changes
global.__objectDepths[167] = -10000; // oA4EscapeControl
global.__objectDepths[168] = -1000; // oA4EscapeExplosion
global.__objectDepths[169] = 0; // oA4EscapeChangeTrigger
global.__objectDepths[170] = 0; // oA4Turbine
global.__objectDepths[171] = 0; // oA4ElecCannon
global.__objectDepths[172] = 0; // oA4ElecBeam
global.__objectDepths[173] = -1000; // oA4EscapeExplosionFail
global.__objectDepths[174] = -110; // oA4SwitchBottomLight
global.__objectDepths[175] = -110; // oA4SwitchLight1
global.__objectDepths[176] = -110; // oA4SwitchLight2
global.__objectDepths[177] = 50; // oA4SwitchCables
global.__objectDepths[178] = 40; // oA4RepairBotSpark
global.__objectDepths[179] = 50; // oA4RepairBot
global.__objectDepths[180] = 1000; // oA4PowerBG
global.__objectDepths[181] = -90; // oA4Rock
global.__objectDepths[182] = -90; // oA4RockTop
global.__objectDepths[183] = 0; // oA4RocksCollision
global.__objectDepths[184] = 90; // oWarpPipeTrigger
global.__objectDepths[185] = 5; // oBattery
global.__objectDepths[186] = -1000; // oBatteryExpl
global.__objectDepths[187] = 5; // oBatterySlot
global.__objectDepths[188] = 50; // oA5CarrierBot
global.__objectDepths[189] = 0; // oBatteryControl
global.__objectDepths[190] = 0; // oBatteryControlMulti
global.__objectDepths[191] = 0; // oA5MainSwitch
global.__objectDepths[192] = 50; // oA5CarrierBotCutscene
global.__objectDepths[193] = 0; // oA5BotSpawnCutscene
global.__objectDepths[194] = 0; // oBatteryRemover
global.__objectDepths[195] = 0; // oBarrier
global.__objectDepths[196] = 1000; // oA5ActivationBG
global.__objectDepths[197] = -200; // oA5SwitchLight
global.__objectDepths[198] = 0; // oEMP
global.__objectDepths[199] = 150; // oWarpPlayerFX
global.__objectDepths[200] = 90; // oGravityPodGlow
global.__objectDepths[201] = 50; // oGravityPod
global.__objectDepths[202] = 0; // oGravityPodTrigger
global.__objectDepths[203] = -200; // oGravityPodLights
global.__objectDepths[204] = -90; // oGravityOverlay
global.__objectDepths[205] = -150; // oA5Vent
global.__objectDepths[206] = 150; // oA5CaveBubbles
global.__objectDepths[207] = 0; // oGFTrooperRed
global.__objectDepths[208] = 0; // oGFTrooperBlue
global.__objectDepths[209] = 0; // oGFTrooperYellow
global.__objectDepths[210] = 0; // oGFTrooperGreen
global.__objectDepths[211] = 0; // oFirstOmegaTrigger
global.__objectDepths[212] = -10; // oGFTBullet1
global.__objectDepths[213] = -1; // oGFTrooperBlueFall
global.__objectDepths[214] = -1; // oGFTrooperRifle
global.__objectDepths[215] = -1; // oGFTrooperYellowFall
global.__objectDepths[216] = 0; // oGFTBullet2
global.__objectDepths[217] = -500; // oA6Dust
global.__objectDepths[218] = 0; // oA6DustSpawner
global.__objectDepths[219] = -10; // oWaterfall
global.__objectDepths[220] = 0; // oMonsterEgg
global.__objectDepths[221] = 0; // oHatchlingTrigger
global.__objectDepths[222] = 0; // oMonsterEggPiece
global.__objectDepths[223] = -90; // oA7Crystal1
global.__objectDepths[224] = -90; // oA7Crystal2
global.__objectDepths[225] = -90; // oA7Crystal3
global.__objectDepths[226] = -90; // oA7Crystal4
global.__objectDepths[227] = -90; // oA7Crystal5
global.__objectDepths[228] = -90; // oA7Crystal6
global.__objectDepths[229] = -90; // oA7Crystal7
global.__objectDepths[230] = 0; // oEggTrigger
global.__objectDepths[231] = -110; // oA7Tank0
global.__objectDepths[232] = -110; // oA7Tank1
global.__objectDepths[233] = -110; // oA7Tank2
global.__objectDepths[234] = -110; // oA7Tank3
global.__objectDepths[235] = -110; // oA7Tank4
global.__objectDepths[236] = -110; // oA7Tank5
global.__objectDepths[237] = -110; // oA7Tank6
global.__objectDepths[238] = -110; // oA7Tank7
global.__objectDepths[239] = -110; // oA7Tank8
global.__objectDepths[240] = 0; // oMonsterDoorControl
global.__objectDepths[241] = 0; // oA7QueenSoundLoop
global.__objectDepths[242] = 80; // oA8CommsScreen
global.__objectDepths[243] = 0; // oA8Lamp
global.__objectDepths[244] = -200; // oA8RedLight
global.__objectDepths[245] = -200; // oGotoRoom
global.__objectDepths[246] = -1000; // oCameraLimit
global.__objectDepths[247] = -200; // oCameraLimitV
global.__objectDepths[248] = -500; // oFadeTiles
global.__objectDepths[249] = -500; // oTilesRandomAlpha
global.__objectDepths[250] = 1000; // oBackground
global.__objectDepths[251] = 0; // oStageRectangle
global.__objectDepths[252] = 150; // oBreedingAreaRectangle
global.__objectDepths[253] = 150; // oBreedingAreaRectangle2
global.__objectDepths[254] = 110; // oPulsatingBG
global.__objectDepths[255] = -1000; // oCameraWallR
global.__objectDepths[256] = -1000; // oCameraWallL
global.__objectDepths[257] = -1000; // oCameraWallD
global.__objectDepths[258] = 0; // oGreyDoorTrigger
global.__objectDepths[259] = 0; // oFirstLavaTrigger
global.__objectDepths[260] = 0; // oMonsterScanTrigger
global.__objectDepths[261] = 0; // oLogScanTrigger
global.__objectDepths[262] = -1000; // oAmbSoundLoop
global.__objectDepths[263] = -99; // oDoor
global.__objectDepths[264] = -200; // oDoorA4
global.__objectDepths[265] = -200; // oDoorA5
global.__objectDepths[266] = -200; // oDoorA8
global.__objectDepths[267] = 1; // oCharacter
global.__objectDepths[268] = 0; // oSolid
global.__objectDepths[269] = 0; // oMovingSolid
global.__objectDepths[270] = 0; // oMoveableSolid
global.__objectDepths[271] = 0; // oPlatform
global.__objectDepths[272] = 0; // oLadder
global.__objectDepths[273] = 0; // oSlope
global.__objectDepths[274] = 0; // oLiquid
global.__objectDepths[275] = 0; // oPickup
global.__objectDepths[276] = 0; // oHPickup
global.__objectDepths[277] = 0; // oHPickupBig
global.__objectDepths[278] = 0; // oMPickup
global.__objectDepths[279] = 0; // oSMPickup
global.__objectDepths[280] = 0; // oPBPickup
global.__objectDepths[281] = 0; // oEnemy
global.__objectDepths[282] = 0; // oEnemyProjectile
global.__objectDepths[283] = 0; // oEnemyDisabled
global.__objectDepths[284] = 0; // oEnemyFrozen
global.__objectDepths[285] = 0; // oEnemyRemover
global.__objectDepths[286] = 0; // oEnemySolid
global.__objectDepths[287] = 0; // oSpikes
global.__objectDepths[288] = 0; // oSpikes1
global.__objectDepths[289] = 0; // oSpikes2
global.__objectDepths[290] = 0; // oSpikes3
global.__objectDepths[291] = 0; // oSpikes4
global.__objectDepths[292] = 0; // oSpikesCeiling
global.__objectDepths[293] = 0; // oPlantSpikes
global.__objectDepths[294] = -150; // oCaveNest
global.__objectDepths[295] = 0; // oCavedropper
global.__objectDepths[296] = 0; // oChuteLeech
global.__objectDepths[297] = -3; // oSeerook
global.__objectDepths[298] = -3; // oMumbo
global.__objectDepths[299] = -3; // oMoheek
global.__objectDepths[300] = -3; // oTsumuri
global.__objectDepths[301] = -3; // oYumbo
global.__objectDepths[302] = -3; // oHornoad
global.__objectDepths[303] = 0; // oHornoadSpit
global.__objectDepths[304] = -3; // oWallfire
global.__objectDepths[305] = 0; // oWallfireProj
global.__objectDepths[306] = -3; // oGullugg
global.__objectDepths[307] = -3; // oNeedler
global.__objectDepths[308] = 0; // oGawron
global.__objectDepths[309] = 0; // oGawronSpawner
global.__objectDepths[310] = -3; // oAutoad
global.__objectDepths[311] = -3; // oShirk
global.__objectDepths[312] = -3; // oAutom
global.__objectDepths[313] = 0; // oAutomLava
global.__objectDepths[314] = -3; // oWallfire2
global.__objectDepths[315] = 0; // oWallfireProj2
global.__objectDepths[316] = -3; // oSenjoo
global.__objectDepths[317] = 0; // oAutrack
global.__objectDepths[318] = 1; // oAutrackProj
global.__objectDepths[319] = -3; // oPincherFly
global.__objectDepths[320] = -3; // oGravitt
global.__objectDepths[321] = -3; // oTPO
global.__objectDepths[322] = 0; // oTPO2
global.__objectDepths[323] = 0; // oSpikePlant
global.__objectDepths[324] = 0; // oYumeeSpawner
global.__objectDepths[325] = 0; // oYumeeSpawnerSP
global.__objectDepths[326] = 0; // oYumee
global.__objectDepths[327] = 0; // oA3Stomper
global.__objectDepths[328] = 0; // oA3Welder
global.__objectDepths[329] = 0; // oA3Slasher
global.__objectDepths[330] = 0; // oGravittShell
global.__objectDepths[331] = -90; // oA3Beam
global.__objectDepths[332] = -150; // oA3BeamLights
global.__objectDepths[333] = -20; // oFlitt
global.__objectDepths[334] = 0; // oOctroll
global.__objectDepths[335] = -3; // oGunzoo
global.__objectDepths[336] = 0; // oGunzooProj1
global.__objectDepths[337] = -20; // oElectricSpark
global.__objectDepths[338] = -10; // oGunzooProj2
global.__objectDepths[339] = -10; // oProboscum
global.__objectDepths[340] = -3; // oShielder
global.__objectDepths[341] = -5; // oShielderShield
global.__objectDepths[342] = 0; // oSkorp
global.__objectDepths[343] = -10; // oSkorpDisc
global.__objectDepths[344] = -3; // oMoto
global.__objectDepths[345] = -5; // oMotoMask
global.__objectDepths[346] = 0; // oHalzyn
global.__objectDepths[347] = -5; // oHalzynShield
global.__objectDepths[348] = 0; // oSkreek
global.__objectDepths[349] = 0; // oSkreekSpawner
global.__objectDepths[350] = -3; // oRoboMine
global.__objectDepths[351] = 0; // oRoboMineProj
global.__objectDepths[352] = 0; // oBladeBot
global.__objectDepths[353] = -3; // oMoheekWater
global.__objectDepths[354] = -3; // oMeboid
global.__objectDepths[355] = 0; // oGlowFly
global.__objectDepths[356] = 0; // oRamulkenTrigger
global.__objectDepths[357] = 0; // oRamulken
global.__objectDepths[358] = -2; // oRamulkenShield
global.__objectDepths[359] = -3; // oDrivel
global.__objectDepths[360] = 5; // oBubble
global.__objectDepths[361] = 5; // oBubble2
global.__objectDepths[362] = 5; // oBubble3
global.__objectDepths[363] = -5; // oLavaSurface
global.__objectDepths[364] = -5; // oDrawLava
global.__objectDepths[365] = 50; // oLavaBGFX
global.__objectDepths[366] = -150; // oWater
global.__objectDepths[367] = -500; // oWater2
global.__objectDepths[368] = -149; // oWaterWave
global.__objectDepths[369] = -145; // oLiquidFilter
global.__objectDepths[370] = 0; // oSplash
global.__objectDepths[371] = 0; // oSmallSplash
global.__objectDepths[372] = 0; // oLavaRise
global.__objectDepths[373] = 0; // oMoveWater
global.__objectDepths[374] = 90; // oWaterBackground
global.__objectDepths[375] = -500; // oWaterFXV2
global.__objectDepths[376] = 0; // oLBubble
global.__objectDepths[377] = 20; // oFXTrail
global.__objectDepths[378] = -1; // oFXAnimSpark
global.__objectDepths[379] = 20; // oBeamTrail
global.__objectDepths[380] = 0; // oRMissile
global.__objectDepths[381] = 0; // oScrewAttack
global.__objectDepths[382] = 0; // oSpeedBoost
global.__objectDepths[383] = -10; // oMflash
global.__objectDepths[384] = -50; // oChargeBeamSpark1
global.__objectDepths[385] = 0; // oChargeBeamSpark2
global.__objectDepths[386] = -4999999; // oSuitChangeFX
global.__objectDepths[387] = -4999999; // oGravitySuitChangeFX
global.__objectDepths[388] = 10; // oSuitChangeFX2
global.__objectDepths[389] = 5; // oSBTrail
global.__objectDepths[390] = 5; // oMBTrail
global.__objectDepths[391] = 5; // oJTrail
global.__objectDepths[392] = -10; // oSaveFX
global.__objectDepths[393] = -10; // oSaveSparks
global.__objectDepths[394] = 0; // oSBSpark
global.__objectDepths[395] = 5; // oCharacterTrail
global.__objectDepths[396] = 5; // oSpaceJumpTrail
global.__objectDepths[397] = -10000; // oScreenFlash
global.__objectDepths[398] = -10000; // oScreenFlash2
global.__objectDepths[399] = 5; // oDebris
global.__objectDepths[400] = 5; // oMetalDebrisBig
global.__objectDepths[401] = 5; // oIceShard
global.__objectDepths[402] = 0; // oSparkParticle
global.__objectDepths[403] = 0; // oQuake
global.__objectDepths[404] = -200; // oBigQuake
global.__objectDepths[405] = 0; // oWaterDrop
global.__objectDepths[406] = -90; // oSpotlight1
global.__objectDepths[407] = -109; // oFlashLight
global.__objectDepths[408] = -109; // oFlashLight2
global.__objectDepths[409] = -300; // oFXFog
global.__objectDepths[410] = 1; // oTransition
global.__objectDepths[411] = 1; // oDeathSequence
global.__objectDepths[412] = 2; // oWhiteParticle
global.__objectDepths[413] = 0; // oExplosionSmoke
global.__objectDepths[414] = 0; // oMakeScrMap
global.__objectDepths[415] = 0; // oRecordVideo
global.__objectDepths[416] = -500; // oScrUpperGreenShadow
global.__objectDepths[417] = -500; // oScrUpperRedShadow
global.__objectDepths[418] = 120; // oScrUpperBGShadow
global.__objectDepths[419] = 120; // oScrLowerBGShadow
global.__objectDepths[420] = 120; // oSrcHorizontalBGShadow
global.__objectDepths[421] = 120; // oScrLeftBGShadow
global.__objectDepths[422] = 120; // oScrRightBGShadow
global.__objectDepths[423] = 120; // oScrVerticalBGShadow
global.__objectDepths[424] = -2000; // oPopupText
global.__objectDepths[425] = -1000; // oEMPNoise
global.__objectDepths[426] = -1; // oFXAnimSparkItem
global.__objectDepths[427] = -5000000; // oControl
global.__objectDepths[428] = -500; // oCamera
global.__objectDepths[429] = -500; // oEventCamera
global.__objectDepths[430] = -500; // oEventCamera2
global.__objectDepths[431] = 0; // oVibrate
global.__objectDepths[432] = -5000002; // oTouchControls
global.__objectDepths[433] = 0; // oObjectCamera
global.__objectDepths[434] = -110; // oBomb
global.__objectDepths[435] = -1000; // oBombExpl
global.__objectDepths[436] = -110; // oPBomb
global.__objectDepths[437] = -1500; // oPBombExpl
global.__objectDepths[438] = -1000; // oMissileExpl
global.__objectDepths[439] = -5; // oBeam
global.__objectDepths[440] = 2; // oMissile
global.__objectDepths[441] = -110; // oBomb2
global.__objectDepths[442] = -11; // oChargeBomb
global.__objectDepths[443] = 10; // oMissileTrail
global.__objectDepths[444] = 0; // oMissileFlame
global.__objectDepths[445] = 0; // oItemBall
global.__objectDepths[446] = 0; // oItemBall2
global.__objectDepths[447] = 0; // oItemBall3
global.__objectDepths[448] = 0; // oItemBall4
global.__objectDepths[449] = 0; // oFakeItemBall
global.__objectDepths[450] = -1; // oItemBomb
global.__objectDepths[451] = -1; // oItemPowergrip
global.__objectDepths[452] = -1; // oItemSpiderBall
global.__objectDepths[453] = -1; // oItemJumpBall
global.__objectDepths[454] = -1; // oItemHijump
global.__objectDepths[455] = -1; // oItemVaria
global.__objectDepths[456] = -1; // oItemSpaceJump
global.__objectDepths[457] = -1; // oItemSpeedBooster
global.__objectDepths[458] = -1; // oItemScrewAttack
global.__objectDepths[459] = -1; // oItemGravity
global.__objectDepths[460] = -1; // oItemCBeam
global.__objectDepths[461] = -1; // oItemIBeam
global.__objectDepths[462] = -1; // oItemWBeam
global.__objectDepths[463] = -1; // oItemSBeam
global.__objectDepths[464] = -1; // oItemPBeam
global.__objectDepths[465] = -1; // oItemMissileTank
global.__objectDepths[466] = -1; // oItemSMissileTank
global.__objectDepths[467] = -1; // oItemPBombTank
global.__objectDepths[468] = -1; // oItemEnergyTank
global.__objectDepths[469] = 0; // oItem
global.__objectDepths[470] = 0; // oGameSelMenu
global.__objectDepths[471] = 0; // oMenuSaveSlot
global.__objectDepths[472] = -1; // oSlotMenu1
global.__objectDepths[473] = -1; // oSlotMenu2
global.__objectDepths[474] = -1; // oSlotMenuErase
global.__objectDepths[475] = -1; // oSlotMenuOverwrite
global.__objectDepths[476] = -20; // oSlotMenuCopy
global.__objectDepths[477] = -50; // oSlotFlash
global.__objectDepths[478] = 0; // oPressStart
global.__objectDepths[479] = -1; // oPressStart2
global.__objectDepths[480] = -10; // oDrawTitleBG
global.__objectDepths[481] = 50; // oTitleAnimation
global.__objectDepths[482] = 0; // oTitleText1
global.__objectDepths[483] = 0; // oTitleText2
global.__objectDepths[484] = -1; // oGameOverMenu
global.__objectDepths[485] = 0; // oGameOverText
global.__objectDepths[486] = 0; // oGalleryMenu
global.__objectDepths[487] = 0; // oGalleryOption
global.__objectDepths[488] = 0; // oMGamma
global.__objectDepths[489] = -10; // oMGammaTriggerProx
global.__objectDepths[490] = 0; // oMGammaElec
global.__objectDepths[491] = 0; // oMGammaGrab
global.__objectDepths[492] = -30; // oMGammaArms
global.__objectDepths[493] = 0; // oMGammaA3BTrigger
global.__objectDepths[494] = 0; // oMGammaMutate
global.__objectDepths[495] = 0; // oMGammaFirstTrigger
global.__objectDepths[496] = 0; // oMAlpha
global.__objectDepths[497] = 0; // oMAlphaShell
global.__objectDepths[498] = -10; // oMAlphaTriggerProx
global.__objectDepths[499] = -10; // oMAlpha2TriggerProx
global.__objectDepths[500] = -10; // oMalpha3TriggerProx
global.__objectDepths[501] = -10; // oMAlphaTriggerA2
global.__objectDepths[502] = -10; // oMAlphaTriggerFirstCocoon
global.__objectDepths[503] = 0; // oMAlphaTriggerA3A
global.__objectDepths[504] = -10; // oMAlphaTriggerA3AL
global.__objectDepths[505] = 0; // oMAlphaFirstTrigger
global.__objectDepths[506] = 0; // oMZeta
global.__objectDepths[507] = -1000; // oMZetaHead
global.__objectDepths[508] = -1000; // oMZetaShield
global.__objectDepths[509] = -200; // oMZetaBodyMask
global.__objectDepths[510] = -10; // oMZetaSlashProj
global.__objectDepths[511] = -10; // oMZetaSlashProj2
global.__objectDepths[512] = -15; // oMZetaProj
global.__objectDepths[513] = -15; // oMZetaProjFX
global.__objectDepths[514] = -10; // oMZeta_Cocoon
global.__objectDepths[515] = 0; // oMZetaDrool
global.__objectDepths[516] = 0; // oMZetaFirstTrigger
global.__objectDepths[517] = -155; // oHatchling
global.__objectDepths[518] = 0; // oHatchlingIntro
global.__objectDepths[519] = -90; // oMEgg1
global.__objectDepths[520] = -90; // oMEgg2
global.__objectDepths[521] = 0; // oMMoverLeft
global.__objectDepths[522] = 0; // oMMoverRight
global.__objectDepths[523] = 0; // oMMoverUp
global.__objectDepths[524] = 0; // oMMoverDown
global.__objectDepths[525] = 0; // oMMoverAccelH
global.__objectDepths[526] = 0; // oMStopRight
global.__objectDepths[527] = 0; // oMStopLeft
global.__objectDepths[528] = 0; // oMStopUp
global.__objectDepths[529] = 0; // oMStopDown
global.__objectDepths[530] = 0; // oMOmega
global.__objectDepths[531] = -1000; // oMOmegaHead
global.__objectDepths[532] = 1; // oMOmegaTail
global.__objectDepths[533] = -200; // oMOmegaMask
global.__objectDepths[534] = -100; // oMOmegaGrab
global.__objectDepths[535] = -100; // oMOmegaGroundHit
global.__objectDepths[536] = 0; // oMOmegaFlame
global.__objectDepths[537] = -50; // oMOmegaMask2
global.__objectDepths[538] = -50; // oMOmegaMask3
global.__objectDepths[539] = -200; // oMOmegaMask4
global.__objectDepths[540] = 0; // oMOmegaTailMutate
global.__objectDepths[541] = -10; // oMOmega_Projectile
global.__objectDepths[542] = 0; // oMonster
global.__objectDepths[543] = -1; // oMonsterSpark
global.__objectDepths[544] = 5; // oQueen
global.__objectDepths[545] = -15; // oQueenHead
global.__objectDepths[546] = 10; // oQueenLegBack
global.__objectDepths[547] = -20; // oQueenLegFront
global.__objectDepths[548] = -10; // oQueenFront
global.__objectDepths[549] = -10; // oQueenProj
global.__objectDepths[550] = -30; // oQueenHeadTop
global.__objectDepths[551] = 0; // oQueenHeadBottom
global.__objectDepths[552] = 0; // oQueenFireball
global.__objectDepths[553] = -100; // oQueenGrab
global.__objectDepths[554] = 10; // oQueenChargeParticle
global.__objectDepths[555] = -15; // oQueenFinalGlow
global.__objectDepths[556] = -900; // oLightRay
global.__objectDepths[557] = 0; // oQueenBloodDrop
global.__objectDepths[558] = -1000; // oQueenFinalExplosion
global.__objectDepths[559] = 0; // oBoss1Trigger
global.__objectDepths[560] = 0; // oBoss1Block
global.__objectDepths[561] = -90; // oBoss1Block2
global.__objectDepths[562] = 0; // oBoss1Block3
global.__objectDepths[563] = -150; // oBoss1Head
global.__objectDepths[564] = -151; // oBoss1Beam
global.__objectDepths[565] = 100; // oBoss1Wheel
global.__objectDepths[566] = 0; // oBoss1FBall
global.__objectDepths[567] = 0; // oBoss1FBExplR
global.__objectDepths[568] = 0; // oBoss1FBExplL
global.__objectDepths[569] = 0; // oBoss1FBall2
global.__objectDepths[570] = 0; // oBoss1FBExpl2
global.__objectDepths[571] = 0; // oBoss1FBall3
global.__objectDepths[572] = 0; // oBoss1FBExpl3
global.__objectDepths[573] = -151; // oBoss1Eyes
global.__objectDepths[574] = 0; // oArachnusIntro
global.__objectDepths[575] = 0; // oArachnusIntro2
global.__objectDepths[576] = -80; // oArachnusStatue
global.__objectDepths[577] = 0; // oArachnusStatuePiece
global.__objectDepths[578] = 0; // oArachnus
global.__objectDepths[579] = 0; // oArachnusFireball1
global.__objectDepths[580] = 0; // oArachnusFBExpl
global.__objectDepths[581] = 0; // oArachnusFBExpl3
global.__objectDepths[582] = -1; // oArachnusFireball2
global.__objectDepths[583] = 0; // oArachnusFireball3
global.__objectDepths[584] = 0; // oArachnusClawProj
global.__objectDepths[585] = 0; // oArachnusSpikes
global.__objectDepths[586] = 0; // oJumpBallAppear
global.__objectDepths[587] = 0; // oArachnusTrigger
global.__objectDepths[588] = 0; // oTorizo
global.__objectDepths[589] = 0; // oTorizo2
global.__objectDepths[590] = 0; // oTorizoFireball
global.__objectDepths[591] = 0; // oTorizoSlashProj
global.__objectDepths[592] = 0; // oTorizoGrab
global.__objectDepths[593] = 0; // oTorizoCam
global.__objectDepths[594] = 0; // oTorizoBottom
global.__objectDepths[595] = 0; // oTorizoCeiling
global.__objectDepths[596] = 0; // oTorizoWall
global.__objectDepths[597] = 0; // oTorizo2Cam
global.__objectDepths[598] = 0; // oTorizoTrigger
global.__objectDepths[599] = -90; // oTorizoSpikes
global.__objectDepths[600] = 0; // oTorizoEgg
global.__objectDepths[601] = 0; // oTorizoGhost
global.__objectDepths[602] = -80; // oTorizoStatue
global.__objectDepths[603] = -110; // oTorizoStatueEye
global.__objectDepths[604] = -90; // oTorizoStatuePiece1
global.__objectDepths[605] = -90; // oTorizoStatuePiece2
global.__objectDepths[606] = -90; // oTorizoStatuePiece3
global.__objectDepths[607] = -90; // oTorizoStatuePiece4
global.__objectDepths[608] = 2; // oTorizoWings
global.__objectDepths[609] = 1; // oTorizoJetFX
global.__objectDepths[610] = 2; // oTesterCannon
global.__objectDepths[611] = -1; // oTesterEye
global.__objectDepths[612] = -20; // oTesterGlass
global.__objectDepths[613] = 2; // oTesterIceBeam
global.__objectDepths[614] = 2; // oTesterIceBeam2
global.__objectDepths[615] = 0; // oTesterIceSpark
global.__objectDepths[616] = -10; // oTesterMissile
global.__objectDepths[617] = -1000; // oTesterMissileExpl
global.__objectDepths[618] = -10; // oTesterPlasmaBeam
global.__objectDepths[619] = 0; // oTesterSpazerBeam
global.__objectDepths[620] = 0; // oTesterWaveBeam
global.__objectDepths[621] = 1; // oTester
global.__objectDepths[622] = -5; // oTesterShield
global.__objectDepths[623] = 0; // oTesterBossTrigger
global.__objectDepths[624] = 0; // oTank
global.__objectDepths[625] = -3; // oTankArm
global.__objectDepths[626] = -1; // oTankBottom
global.__objectDepths[627] = -4; // oTankCannon
global.__objectDepths[628] = -1; // oTankCore
global.__objectDepths[629] = 0; // oTankHead
global.__objectDepths[630] = 0; // oTankProjectile
global.__objectDepths[631] = -2; // oTankShield
global.__objectDepths[632] = 0; // oTankBossTrigger
global.__objectDepths[633] = 0; // oTankCam
global.__objectDepths[634] = -80; // oEris
global.__objectDepths[635] = 0; // oErisBody1
global.__objectDepths[636] = 0; // oErisBody2
global.__objectDepths[637] = 0; // oErisBody3
global.__objectDepths[638] = 0; // oErisTail
global.__objectDepths[639] = 0; // oErisBossTrigger
global.__objectDepths[640] = 0; // oGenesis
global.__objectDepths[641] = 0; // oGenesisTrigger
global.__objectDepths[642] = -1; // oGenesisAcid
global.__objectDepths[643] = -10; // oGenesisSlashProj
global.__objectDepths[644] = 0; // oA8RedLightFX
global.__objectDepths[645] = 0; // oGotoEnd
global.__objectDepths[646] = 0; // oMusicFadeout
global.__objectDepths[647] = -5; // oEventSolid1
global.__objectDepths[648] = -150; // oEventSolid2
global.__objectDepths[649] = 0; // oDrawDemoStats
global.__objectDepths[650] = -30; // oDemoIntroSuit
global.__objectDepths[651] = 0; // oFloorButton1
global.__objectDepths[652] = 0; // oDemoStoryScroll
global.__objectDepths[653] = 0; // oTextFadeIn
global.__objectDepths[654] = -10; // oDemoPressStart1
global.__objectDepths[655] = -10; // oDemoPressStart2
global.__objectDepths[656] = 0; // oDemoV2
global.__objectDepths[657] = 0; // oDemoEndSeq
global.__objectDepths[658] = -10000; // oMusicV2
global.__objectDepths[659] = 0; // oGameIntroSeq1
global.__objectDepths[660] = 0; // oLog
global.__objectDepths[661] = -1; // oLogScreen
global.__objectDepths[662] = 0; // oMapBlock
global.__objectDepths[663] = 0; // oDrawMap
global.__objectDepths[664] = -10; // oMapCursor
global.__objectDepths[665] = 100; // oMapScrBG
global.__objectDepths[666] = -100; // oMapScrBG2
global.__objectDepths[667] = -90; // oMapScrBG3
global.__objectDepths[668] = 0; // oDrawMap2
global.__objectDepths[669] = -9; // oMapMarker
global.__objectDepths[670] = 0; // oMapCamera
global.__objectDepths[671] = 100; // oSS_Bg
global.__objectDepths[672] = -100; // oSS_Fg
global.__objectDepths[673] = 0; // oSS_Control
global.__objectDepths[674] = -15; // oSubScrChange
global.__objectDepths[675] = 0; // oPauseOption
global.__objectDepths[676] = -10; // oNormalOption
global.__objectDepths[677] = -10; // oNormalOptionC
global.__objectDepths[678] = -10; // oNormalOptionR
global.__objectDepths[679] = 0; // oOptionLR
global.__objectDepths[680] = 0; // oOptionSlider
global.__objectDepths[681] = -10; // oMenuLabel
global.__objectDepths[682] = -10; // oMenuLabelR
global.__objectDepths[683] = 0; // oPauseMenuOptions
global.__objectDepths[684] = 0; // oOptionsMain
global.__objectDepths[685] = 0; // oOptionsDisplay
global.__objectDepths[686] = 0; // oOptionsSound
global.__objectDepths[687] = 0; // oOptionsControl
global.__objectDepths[688] = 0; // oOptionsKeyboard
global.__objectDepths[689] = 0; // oOptionsJoypad
global.__objectDepths[690] = 0; // oOptionsXJoypad
global.__objectDepths[691] = 0; // oOptionsQuit
global.__objectDepths[692] = 0; // oOptionsReload
global.__objectDepths[693] = 100; // oOptionsBG
global.__objectDepths[694] = -100; // oOptionsFG
global.__objectDepths[695] = -10; // oSubScreenSuit
global.__objectDepths[696] = -10; // oSubScreenBeam
global.__objectDepths[697] = -10; // oSubScreenMisc
global.__objectDepths[698] = -10; // oSubScreenBoots
global.__objectDepths[699] = -1; // oSubScrPlayer
global.__objectDepths[700] = -20; // oSubScrTopLayer
global.__objectDepths[701] = 0; // oSubscreenMenu
global.__objectDepths[702] = 0; // oLogEntry
global.__objectDepths[703] = 0; // oLogScreenControl
global.__objectDepths[704] = 0; // oLoadGame
global.__objectDepths[705] = 0; // oDemoEndTrigger
global.__objectDepths[706] = 0; // oDemoEndObj
global.__objectDepths[707] = 0; // oItemCutscene
global.__objectDepths[708] = 0; // oIntroController
global.__objectDepths[709] = 10; // oIntroCutscene
global.__objectDepths[710] = 0; // oIntroShip2
global.__objectDepths[711] = 0; // oIntroShip1
global.__objectDepths[712] = 0; // oIntroShip3
global.__objectDepths[713] = -10; // oIntroClouds
global.__objectDepths[714] = 0; // oIntroText1
global.__objectDepths[715] = 0; // oNewGameIntro
global.__objectDepths[716] = 0; // oScoreScreen
global.__objectDepths[717] = 0; // oCreditsText
global.__objectDepths[718] = 0; // oCreditsShip
global.__objectDepths[719] = 0; // oHintTrigger
global.__objectDepths[720] = 0; // oHTriggerDiag
global.__objectDepths[721] = 0; // oHTriggerMorph
global.__objectDepths[722] = 0; // oHTriggerDiag2
global.__objectDepths[723] = 0; // oHTriggerMissiles
global.__objectDepths[724] = 0; // oHTriggerAutoad
global.__objectDepths[725] = 0; // oHintDoneTrigger
global.__objectDepths[726] = -1100; // oNotification
global.__objectDepths[727] = -1100; // oScanning
global.__objectDepths[728] = -1100; // oScanMonster
global.__objectDepths[729] = -1000; // oLightEngine
global.__objectDepths[730] = 0; // oLight
global.__objectDepths[731] = 0; // oLight64
global.__objectDepths[732] = 0; // oFlashlight64
global.__objectDepths[733] = 0; // oLight32
global.__objectDepths[734] = 0; // oLight16
global.__objectDepths[735] = 0; // oLight64Red
global.__objectDepths[736] = 0; // oLight64Blue
global.__objectDepths[737] = 0; // oFadeLight32
global.__objectDepths[738] = 0; // oFadeLight64
global.__objectDepths[739] = 0; // Rooma3c03Fix
global.__objectDepths[740] = 0; // rm_a4a01_Fix
global.__objectDepths[741] = 0; // Rooma4b11Fix
global.__objectDepths[742] = -1; // oSlotMenu_gametypes
global.__objectDepths[743] = -1; // oSlotMenu_classic
global.__objectDepths[744] = -1; // oSlotMenu_random
global.__objectDepths[745] = -1; // oSlotMenu_normal_only
global.__objectDepths[746] = -1; // oSlotMenu_Fusion
global.__objectDepths[747] = 90; // oWarpDoorBroken
global.__objectDepths[748] = -90; // oSaveStationBroken
global.__objectDepths[749] = 0; // oRm_a5c11lock
global.__objectDepths[750] = 0; // godmode_GD
global.__objectDepths[751] = 0; // hatchling_freeze
global.__objectDepths[752] = 0; // oOptionsExtras
global.__objectDepths[753] = -200; // oBigQuakeQueen
global.__objectDepths[754] = -1; // oItemM_52
global.__objectDepths[755] = -1; // oItemM_53
global.__objectDepths[756] = -1; // oItemM_54
global.__objectDepths[757] = -1; // oItemM_55
global.__objectDepths[758] = -1; // oItemM_56
global.__objectDepths[759] = -1; // oItemM_57
global.__objectDepths[760] = -1; // oItemM_60
global.__objectDepths[761] = -1; // oItemM_100
global.__objectDepths[762] = -1; // oItemM_101
global.__objectDepths[763] = -1; // oItemM_102
global.__objectDepths[764] = -1; // oItemM_104
global.__objectDepths[765] = -1; // oItemM_105
global.__objectDepths[766] = -1; // oItemM_106
global.__objectDepths[767] = -1; // oItemM_107
global.__objectDepths[768] = -1; // oItemM_109
global.__objectDepths[769] = -1; // oItemM_111
global.__objectDepths[770] = -1; // oItemM_150
global.__objectDepths[771] = -1; // oItemM_151
global.__objectDepths[772] = -1; // oItemM_152
global.__objectDepths[773] = -1; // oItemM_153
global.__objectDepths[774] = -1; // oItemM_154
global.__objectDepths[775] = -1; // oItemM_155
global.__objectDepths[776] = -1; // oItemM_156
global.__objectDepths[777] = -1; // oItemM_159
global.__objectDepths[778] = -1; // oItemM_161
global.__objectDepths[779] = -1; // oItemM_163
global.__objectDepths[780] = -1; // oItemM_202
global.__objectDepths[781] = -1; // oItemM_203
global.__objectDepths[782] = -1; // oItemM_204
global.__objectDepths[783] = -1; // oItemM_205
global.__objectDepths[784] = -1; // oItemM_208
global.__objectDepths[785] = -1; // oItemM_210
global.__objectDepths[786] = -1; // oItemM_211
global.__objectDepths[787] = -1; // oItemM_214
global.__objectDepths[788] = -1; // oItemM_250
global.__objectDepths[789] = -1; // oItemM_252
global.__objectDepths[790] = -1; // oItemM_255
global.__objectDepths[791] = -1; // oItemM_257
global.__objectDepths[792] = -1; // oItemM_259
global.__objectDepths[793] = -1; // oItemM_303
global.__objectDepths[794] = -1; // oItemM_304
global.__objectDepths[795] = -1; // oItemM_307
global.__objectDepths[796] = -1; // oItemM_308
global.__objectDepths[797] = -1; // oItemM_309
global.__objectDepths[798] = -1; // oItemSM_51
global.__objectDepths[799] = -1; // oItemSM_110
global.__objectDepths[800] = -1; // oItemSM_162
global.__objectDepths[801] = -1; // oItemSM_206
global.__objectDepths[802] = -1; // oItemSM_207
global.__objectDepths[803] = -1; // oItemSM_209
global.__objectDepths[804] = -1; // oItemSM_215
global.__objectDepths[805] = -1; // oItemSM_256
global.__objectDepths[806] = -1; // oItemSM_300
global.__objectDepths[807] = -1; // oItemSM_305
global.__objectDepths[808] = -1; // oItemETank_50
global.__objectDepths[809] = -1; // oItemETank_103
global.__objectDepths[810] = -1; // oItemETank_108
global.__objectDepths[811] = -1; // oItemETank_157
global.__objectDepths[812] = -1; // oItemETank_158
global.__objectDepths[813] = -1; // oItemETank_200
global.__objectDepths[814] = -1; // oItemETank_201
global.__objectDepths[815] = -1; // oItemETank_251
global.__objectDepths[816] = -1; // oItemETank_254
global.__objectDepths[817] = -1; // oItemETank_306
global.__objectDepths[818] = -1; // oItemPB_58
global.__objectDepths[819] = -1; // oItemPB_59
global.__objectDepths[820] = -1; // oItemPB_112
global.__objectDepths[821] = -1; // oItemPB_160
global.__objectDepths[822] = -1; // oItemPB_212
global.__objectDepths[823] = -1; // oItemPB_213
global.__objectDepths[824] = -1; // oItemPB_253
global.__objectDepths[825] = -1; // oItemPB_258
global.__objectDepths[826] = -1; // oItemPB_301
global.__objectDepths[827] = -1; // oItemPB_302
global.__objectDepths[828] = -200; // oXPickup
global.__objectDepths[829] = 0; // oHXPickup
global.__objectDepths[830] = 0; // oHXPickupBig
global.__objectDepths[831] = 0; // oMXPickup
global.__objectDepths[832] = 0; // oSMXPickup
global.__objectDepths[833] = 0; // oPBXPickup
global.__objectDepths[834] = -122; // oAbsorbX
global.__objectDepths[835] = -4; // oBlobThrowerWater
global.__objectDepths[836] = -4; // oBlobThrowerLand
global.__objectDepths[837] = -3; // oBlobWater
global.__objectDepths[838] = -3; // oBlobAir
global.__objectDepths[839] = 0; // oBlobSolid
global.__objectDepths[840] = 0; // oBarrier2
global.__objectDepths[841] = -3; // oMeboid2
global.__objectDepths[842] = 0; // oSkreek2
global.__objectDepths[843] = 0; // oSkreekSpit
global.__objectDepths[844] = 0; // oSkreekTrigger
global.__objectDepths[845] = 0; // oSkorpLure
global.__objectDepths[846] = -2; // oDrivelProj
global.__objectDepths[847] = 0; // oEndingHornoad
global.__objectDepths[848] = 1; // oEndingCrystal
global.__objectDepths[849] = 0; // oEndingCrystal1
global.__objectDepths[850] = 0; // oEndingCrystal2
global.__objectDepths[851] = 0; // oEndingCrystal3
global.__objectDepths[852] = 0; // oEndingCrystal4
global.__objectDepths[853] = 0; // oEndingCrystal5
global.__objectDepths[854] = -99999; // oEndingFadein
global.__objectDepths[855] = -99999; // oEndingFadeout
global.__objectDepths[856] = 1; // oHornoadSkeleton
global.__objectDepths[857] = -2; // oEndingMonsterEgg
global.__objectDepths[858] = -3; // oEndingHornoadFX
global.__objectDepths[859] = 0; // oEndingCrystalParent
global.__objectDepths[860] = 0; // oEndingSkip
global.__objectDepths[861] = 0; // oEndingSolid
global.__objectDepths[862] = 0; // oErisHead
global.__objectDepths[863] = 0; // oErisSegment
global.__objectDepths[864] = 0; // oErisTarget1
global.__objectDepths[865] = 0; // oErisTarget2
global.__objectDepths[866] = 0; // oErisTarget3
global.__objectDepths[867] = 0; // oErisTarget4
global.__objectDepths[868] = 0; // oErisTarget5
global.__objectDepths[869] = 0; // oErisTarget6
global.__objectDepths[870] = -1; // oErisProjectile
global.__objectDepths[871] = -100; // oErisPipe
global.__objectDepths[872] = -99999999; // oIGT
global.__objectDepths[873] = 0; // oGameOverBG
global.__objectDepths[874] = 0; // oOptionsGame
global.__objectDepths[875] = 0; // oOptionSeed
global.__objectDepths[876] = 0; // oLogTrigger
global.__objectDepths[877] = 90; // oBabySeptogg
global.__objectDepths[878] = 90; // oElderSeptogg
global.__objectDepths[879] = -153; // oCoreX
global.__objectDepths[880] = -155; // oCoreXShell
global.__objectDepths[881] = -154; // oElectricSparkCoreX
global.__objectDepths[882] = -154; // oElectricSparkCoreXShort
global.__objectDepths[883] = 0; // oOptionsMogaJoypad
global.__objectDepths[884] = 0; // oTorizoCoreXCam
global.__objectDepths[885] = 0; // oChozoLogMarker
global.__objectDepths[886] = 0; // A5_Alpha_Septogg_Checker
global.__objectDepths[887] = 0; // oCheats
global.__objectDepths[888] = 0; // oShroom
global.__objectDepths[889] = 10; // oShroomU
global.__objectDepths[890] = 10; // oCordCrystal
global.__objectDepths[891] = 10; // oShroomC
global.__objectDepths[892] = 0; // oAreaIntro
global.__objectDepths[893] = -200; // oA3_Missiles_Glow
global.__objectDepths[894] = 0; // oStartupControl


global.__objectNames[0] = "oTestKeys";
global.__objectNames[1] = "oNumberOverlayFade";
global.__objectNames[2] = "oPlayback";
global.__objectNames[3] = "oRecord";
global.__objectNames[4] = "oSolid1";
global.__objectNames[5] = "oSlope1";
global.__objectNames[6] = "oSlope2";
global.__objectNames[7] = "oSlope3";
global.__objectNames[8] = "oSlope4";
global.__objectNames[9] = "oSlope1B";
global.__objectNames[10] = "oSlope2B";
global.__objectNames[11] = "oSlope3B";
global.__objectNames[12] = "oSlope4B";
global.__objectNames[13] = "oSlopeFL1";
global.__objectNames[14] = "oSlopeFL2";
global.__objectNames[15] = "oSlopeFL1B";
global.__objectNames[16] = "oSlopeFL2B";
global.__objectNames[17] = "oSolid2x1";
global.__objectNames[18] = "oSolid1x2";
global.__objectNames[19] = "oSolid4x1";
global.__objectNames[20] = "oSolid1x4";
global.__objectNames[21] = "oSolid8x1";
global.__objectNames[22] = "oSolid1x8";
global.__objectNames[23] = "oSolid2x2";
global.__objectNames[24] = "oSolidItem";
global.__objectNames[25] = "oBlockShoot";
global.__objectNames[26] = "oBlockShootChain";
global.__objectNames[27] = "oBlockBomb";
global.__objectNames[28] = "oBlockBombChain";
global.__objectNames[29] = "oBlockBombItem";
global.__objectNames[30] = "oBlockScrew";
global.__objectNames[31] = "oBlockPBomb";
global.__objectNames[32] = "oBlockPBombChain";
global.__objectNames[33] = "oBlockMissile";
global.__objectNames[34] = "oBlockSMissile";
global.__objectNames[35] = "oBlockSpeed";
global.__objectNames[36] = "oBlockSand";
global.__objectNames[37] = "oBlockStep";
global.__objectNames[38] = "oDestroyedBlock";
global.__objectNames[39] = "oMoverUp";
global.__objectNames[40] = "oMoverDown";
global.__objectNames[41] = "oMoverLeft";
global.__objectNames[42] = "oMoverLeftUp";
global.__objectNames[43] = "oMoverRight";
global.__objectNames[44] = "oSpikeSolid";
global.__objectNames[45] = "oSolid1Normal";
global.__objectNames[46] = "oSolid2x1Normal";
global.__objectNames[47] = "oSolid4x1Normal";
global.__objectNames[48] = "oSolid8x1Normal";
global.__objectNames[49] = "oSlope1Normal";
global.__objectNames[50] = "oSlope2Normal";
global.__objectNames[51] = "oSlope1BNormal";
global.__objectNames[52] = "oSlope2BNormal";
global.__objectNames[53] = "oSolid2x2Normal";
global.__objectNames[54] = "oSolid1Rock";
global.__objectNames[55] = "oSolid2x1Rock";
global.__objectNames[56] = "oSolid4x1Rock";
global.__objectNames[57] = "oSolid8x1Rock";
global.__objectNames[58] = "oSlope1Rock";
global.__objectNames[59] = "oSlope2Rock";
global.__objectNames[60] = "oSlope1BRock";
global.__objectNames[61] = "oSlope2BRock";
global.__objectNames[62] = "oSolid2x2Rock";
global.__objectNames[63] = "oSolid1Grass";
global.__objectNames[64] = "oSolid2x1Grass";
global.__objectNames[65] = "oSolid4x1Grass";
global.__objectNames[66] = "oSolid8x1Grass";
global.__objectNames[67] = "oSlope1Grass";
global.__objectNames[68] = "oSlope2Grass";
global.__objectNames[69] = "oSlope1BGrass";
global.__objectNames[70] = "oSlope2BGrass";
global.__objectNames[71] = "oSolid2x2Grass";
global.__objectNames[72] = "oSolid1Stone";
global.__objectNames[73] = "oSolid2x1Stone";
global.__objectNames[74] = "oSolid4x1Stone";
global.__objectNames[75] = "oSolid8x1Stone";
global.__objectNames[76] = "oSlope1Stone";
global.__objectNames[77] = "oSlope2Stone";
global.__objectNames[78] = "oSlope1BStone";
global.__objectNames[79] = "oSlope2BStone";
global.__objectNames[80] = "oSolid2x2Stone";
global.__objectNames[81] = "oSolid1Metal";
global.__objectNames[82] = "oSolid2x1Metal";
global.__objectNames[83] = "oSolid4x1Metal";
global.__objectNames[84] = "oSolid8x1Metal";
global.__objectNames[85] = "oSlope1Metal";
global.__objectNames[86] = "oSlope2Metal";
global.__objectNames[87] = "oSlope1BMetal";
global.__objectNames[88] = "oSlope2BMetal";
global.__objectNames[89] = "oSolid2x2Metal";
global.__objectNames[90] = "oSolid1Wet";
global.__objectNames[91] = "oSolid2x1Wet";
global.__objectNames[92] = "oSolid4x1Wet";
global.__objectNames[93] = "oSolid8x1Wet";
global.__objectNames[94] = "oSlope1Wet";
global.__objectNames[95] = "oSlope2Wet";
global.__objectNames[96] = "oSlope1BWet";
global.__objectNames[97] = "oSlope2BWet";
global.__objectNames[98] = "oSolid2x2Wet";
global.__objectNames[99] = "oPlatform1";
global.__objectNames[100] = "oSaveStation";
global.__objectNames[101] = "oSaveStation2";
global.__objectNames[102] = "oElevator";
global.__objectNames[103] = "oGFElevator";
global.__objectNames[104] = "oGFElevatorFX";
global.__objectNames[105] = "oSaveShip";
global.__objectNames[106] = "oDecoration";
global.__objectNames[107] = "oMEgg2A";
global.__objectNames[108] = "oShip1";
global.__objectNames[109] = "oShipOutro";
global.__objectNames[110] = "oFinalFadeout";
global.__objectNames[111] = "oA1MovingPlatform";
global.__objectNames[112] = "oA1MovingPlatformBG";
global.__objectNames[113] = "oClawOrb";
global.__objectNames[114] = "oClawPuzzle";
global.__objectNames[115] = "oClawOrbFirst";
global.__objectNames[116] = "oA1MovingPlatform2";
global.__objectNames[117] = "oA2BigTurbine";
global.__objectNames[118] = "oA2SmallTurbine";
global.__objectNames[119] = "oCurrentBubble";
global.__objectNames[120] = "oBubbleSpawner";
global.__objectNames[121] = "oA2WaterJetMachine";
global.__objectNames[122] = "oA2WJValve";
global.__objectNames[123] = "oA2WJStop";
global.__objectNames[124] = "oA2WaterSpawner";
global.__objectNames[125] = "oA2WJWaterA";
global.__objectNames[126] = "oA2WJWaterC";
global.__objectNames[127] = "oA2WJWaterA2";
global.__objectNames[128] = "oA2WaterStream";
global.__objectNames[129] = "oMovingPlatform1";
global.__objectNames[130] = "oMachine1Core";
global.__objectNames[131] = "oMachine1Beam";
global.__objectNames[132] = "oMovingPlatform2";
global.__objectNames[133] = "oMovingPlatform2B";
global.__objectNames[134] = "oMovingPlatform2C";
global.__objectNames[135] = "oGlowPlant1";
global.__objectNames[136] = "oGlowPlant2";
global.__objectNames[137] = "oGlowPlant3";
global.__objectNames[138] = "oGlowPlant4";
global.__objectNames[139] = "oA3AssemblyControl";
global.__objectNames[140] = "oAutoadPlayer";
global.__objectNames[141] = "oAutoadCamera";
global.__objectNames[142] = "oAutoadControlTrigger";
global.__objectNames[143] = "oAutoadMissile";
global.__objectNames[144] = "oDrillTrigger1";
global.__objectNames[145] = "oDrillSeq1";
global.__objectNames[146] = "oDrillTrigger2";
global.__objectNames[147] = "oDrillSeq2";
global.__objectNames[148] = "oDrillBack";
global.__objectNames[149] = "oDrillFront";
global.__objectNames[150] = "oDrillWall";
global.__objectNames[151] = "oGreenCrystal";
global.__objectNames[152] = "oA3LabLight";
global.__objectNames[153] = "oA3LabDoor";
global.__objectNames[154] = "oLightBug";
global.__objectNames[155] = "oGreenCrystalShard";
global.__objectNames[156] = "oLabEntranceControl";
global.__objectNames[157] = "oArea4PowerSwitch";
global.__objectNames[158] = "oA4TileLight1";
global.__objectNames[159] = "oA4TileLight2";
global.__objectNames[160] = "oA4TileLight3";
global.__objectNames[161] = "oA4TileLight4";
global.__objectNames[162] = "oA4TileLight5";
global.__objectNames[163] = "oA4PowerCell";
global.__objectNames[164] = "oA4EscapeSeqFX";
global.__objectNames[165] = "oA4BlastDoor";
global.__objectNames[166] = "oA4B14Changes";
global.__objectNames[167] = "oA4EscapeControl";
global.__objectNames[168] = "oA4EscapeExplosion";
global.__objectNames[169] = "oA4EscapeChangeTrigger";
global.__objectNames[170] = "oA4Turbine";
global.__objectNames[171] = "oA4ElecCannon";
global.__objectNames[172] = "oA4ElecBeam";
global.__objectNames[173] = "oA4EscapeExplosionFail";
global.__objectNames[174] = "oA4SwitchBottomLight";
global.__objectNames[175] = "oA4SwitchLight1";
global.__objectNames[176] = "oA4SwitchLight2";
global.__objectNames[177] = "oA4SwitchCables";
global.__objectNames[178] = "oA4RepairBotSpark";
global.__objectNames[179] = "oA4RepairBot";
global.__objectNames[180] = "oA4PowerBG";
global.__objectNames[181] = "oA4Rock";
global.__objectNames[182] = "oA4RockTop";
global.__objectNames[183] = "oA4RocksCollision";
global.__objectNames[184] = "oWarpPipeTrigger";
global.__objectNames[185] = "oBattery";
global.__objectNames[186] = "oBatteryExpl";
global.__objectNames[187] = "oBatterySlot";
global.__objectNames[188] = "oA5CarrierBot";
global.__objectNames[189] = "oBatteryControl";
global.__objectNames[190] = "oBatteryControlMulti";
global.__objectNames[191] = "oA5MainSwitch";
global.__objectNames[192] = "oA5CarrierBotCutscene";
global.__objectNames[193] = "oA5BotSpawnCutscene";
global.__objectNames[194] = "oBatteryRemover";
global.__objectNames[195] = "oBarrier";
global.__objectNames[196] = "oA5ActivationBG";
global.__objectNames[197] = "oA5SwitchLight";
global.__objectNames[198] = "oEMP";
global.__objectNames[199] = "oWarpPlayerFX";
global.__objectNames[200] = "oGravityPodGlow";
global.__objectNames[201] = "oGravityPod";
global.__objectNames[202] = "oGravityPodTrigger";
global.__objectNames[203] = "oGravityPodLights";
global.__objectNames[204] = "oGravityOverlay";
global.__objectNames[205] = "oA5Vent";
global.__objectNames[206] = "oA5CaveBubbles";
global.__objectNames[207] = "oGFTrooperRed";
global.__objectNames[208] = "oGFTrooperBlue";
global.__objectNames[209] = "oGFTrooperYellow";
global.__objectNames[210] = "oGFTrooperGreen";
global.__objectNames[211] = "oFirstOmegaTrigger";
global.__objectNames[212] = "oGFTBullet1";
global.__objectNames[213] = "oGFTrooperBlueFall";
global.__objectNames[214] = "oGFTrooperRifle";
global.__objectNames[215] = "oGFTrooperYellowFall";
global.__objectNames[216] = "oGFTBullet2";
global.__objectNames[217] = "oA6Dust";
global.__objectNames[218] = "oA6DustSpawner";
global.__objectNames[219] = "oWaterfall";
global.__objectNames[220] = "oMonsterEgg";
global.__objectNames[221] = "oHatchlingTrigger";
global.__objectNames[222] = "oMonsterEggPiece";
global.__objectNames[223] = "oA7Crystal1";
global.__objectNames[224] = "oA7Crystal2";
global.__objectNames[225] = "oA7Crystal3";
global.__objectNames[226] = "oA7Crystal4";
global.__objectNames[227] = "oA7Crystal5";
global.__objectNames[228] = "oA7Crystal6";
global.__objectNames[229] = "oA7Crystal7";
global.__objectNames[230] = "oEggTrigger";
global.__objectNames[231] = "oA7Tank0";
global.__objectNames[232] = "oA7Tank1";
global.__objectNames[233] = "oA7Tank2";
global.__objectNames[234] = "oA7Tank3";
global.__objectNames[235] = "oA7Tank4";
global.__objectNames[236] = "oA7Tank5";
global.__objectNames[237] = "oA7Tank6";
global.__objectNames[238] = "oA7Tank7";
global.__objectNames[239] = "oA7Tank8";
global.__objectNames[240] = "oMonsterDoorControl";
global.__objectNames[241] = "oA7QueenSoundLoop";
global.__objectNames[242] = "oA8CommsScreen";
global.__objectNames[243] = "oA8Lamp";
global.__objectNames[244] = "oA8RedLight";
global.__objectNames[245] = "oGotoRoom";
global.__objectNames[246] = "oCameraLimit";
global.__objectNames[247] = "oCameraLimitV";
global.__objectNames[248] = "oFadeTiles";
global.__objectNames[249] = "oTilesRandomAlpha";
global.__objectNames[250] = "oBackground";
global.__objectNames[251] = "oStageRectangle";
global.__objectNames[252] = "oBreedingAreaRectangle";
global.__objectNames[253] = "oBreedingAreaRectangle2";
global.__objectNames[254] = "oPulsatingBG";
global.__objectNames[255] = "oCameraWallR";
global.__objectNames[256] = "oCameraWallL";
global.__objectNames[257] = "oCameraWallD";
global.__objectNames[258] = "oGreyDoorTrigger";
global.__objectNames[259] = "oFirstLavaTrigger";
global.__objectNames[260] = "oMonsterScanTrigger";
global.__objectNames[261] = "oLogScanTrigger";
global.__objectNames[262] = "oAmbSoundLoop";
global.__objectNames[263] = "oDoor";
global.__objectNames[264] = "oDoorA4";
global.__objectNames[265] = "oDoorA5";
global.__objectNames[266] = "oDoorA8";
global.__objectNames[267] = "oCharacter";
global.__objectNames[268] = "oSolid";
global.__objectNames[269] = "oMovingSolid";
global.__objectNames[270] = "oMoveableSolid";
global.__objectNames[271] = "oPlatform";
global.__objectNames[272] = "oLadder";
global.__objectNames[273] = "oSlope";
global.__objectNames[274] = "oLiquid";
global.__objectNames[275] = "oPickup";
global.__objectNames[276] = "oHPickup";
global.__objectNames[277] = "oHPickupBig";
global.__objectNames[278] = "oMPickup";
global.__objectNames[279] = "oSMPickup";
global.__objectNames[280] = "oPBPickup";
global.__objectNames[281] = "oEnemy";
global.__objectNames[282] = "oEnemyProjectile";
global.__objectNames[283] = "oEnemyDisabled";
global.__objectNames[284] = "oEnemyFrozen";
global.__objectNames[285] = "oEnemyRemover";
global.__objectNames[286] = "oEnemySolid";
global.__objectNames[287] = "oSpikes";
global.__objectNames[288] = "oSpikes1";
global.__objectNames[289] = "oSpikes2";
global.__objectNames[290] = "oSpikes3";
global.__objectNames[291] = "oSpikes4";
global.__objectNames[292] = "oSpikesCeiling";
global.__objectNames[293] = "oPlantSpikes";
global.__objectNames[294] = "oCaveNest";
global.__objectNames[295] = "oCavedropper";
global.__objectNames[296] = "oChuteLeech";
global.__objectNames[297] = "oSeerook";
global.__objectNames[298] = "oMumbo";
global.__objectNames[299] = "oMoheek";
global.__objectNames[300] = "oTsumuri";
global.__objectNames[301] = "oYumbo";
global.__objectNames[302] = "oHornoad";
global.__objectNames[303] = "oHornoadSpit";
global.__objectNames[304] = "oWallfire";
global.__objectNames[305] = "oWallfireProj";
global.__objectNames[306] = "oGullugg";
global.__objectNames[307] = "oNeedler";
global.__objectNames[308] = "oGawron";
global.__objectNames[309] = "oGawronSpawner";
global.__objectNames[310] = "oAutoad";
global.__objectNames[311] = "oShirk";
global.__objectNames[312] = "oAutom";
global.__objectNames[313] = "oAutomLava";
global.__objectNames[314] = "oWallfire2";
global.__objectNames[315] = "oWallfireProj2";
global.__objectNames[316] = "oSenjoo";
global.__objectNames[317] = "oAutrack";
global.__objectNames[318] = "oAutrackProj";
global.__objectNames[319] = "oPincherFly";
global.__objectNames[320] = "oGravitt";
global.__objectNames[321] = "oTPO";
global.__objectNames[322] = "oTPO2";
global.__objectNames[323] = "oSpikePlant";
global.__objectNames[324] = "oYumeeSpawner";
global.__objectNames[325] = "oYumeeSpawnerSP";
global.__objectNames[326] = "oYumee";
global.__objectNames[327] = "oA3Stomper";
global.__objectNames[328] = "oA3Welder";
global.__objectNames[329] = "oA3Slasher";
global.__objectNames[330] = "oGravittShell";
global.__objectNames[331] = "oA3Beam";
global.__objectNames[332] = "oA3BeamLights";
global.__objectNames[333] = "oFlitt";
global.__objectNames[334] = "oOctroll";
global.__objectNames[335] = "oGunzoo";
global.__objectNames[336] = "oGunzooProj1";
global.__objectNames[337] = "oElectricSpark";
global.__objectNames[338] = "oGunzooProj2";
global.__objectNames[339] = "oProboscum";
global.__objectNames[340] = "oShielder";
global.__objectNames[341] = "oShielderShield";
global.__objectNames[342] = "oSkorp";
global.__objectNames[343] = "oSkorpDisc";
global.__objectNames[344] = "oMoto";
global.__objectNames[345] = "oMotoMask";
global.__objectNames[346] = "oHalzyn";
global.__objectNames[347] = "oHalzynShield";
global.__objectNames[348] = "oSkreek";
global.__objectNames[349] = "oSkreekSpawner";
global.__objectNames[350] = "oRoboMine";
global.__objectNames[351] = "oRoboMineProj";
global.__objectNames[352] = "oBladeBot";
global.__objectNames[353] = "oMoheekWater";
global.__objectNames[354] = "oMeboid";
global.__objectNames[355] = "oGlowFly";
global.__objectNames[356] = "oRamulkenTrigger";
global.__objectNames[357] = "oRamulken";
global.__objectNames[358] = "oRamulkenShield";
global.__objectNames[359] = "oDrivel";
global.__objectNames[360] = "oBubble";
global.__objectNames[361] = "oBubble2";
global.__objectNames[362] = "oBubble3";
global.__objectNames[363] = "oLavaSurface";
global.__objectNames[364] = "oDrawLava";
global.__objectNames[365] = "oLavaBGFX";
global.__objectNames[366] = "oWater";
global.__objectNames[367] = "oWater2";
global.__objectNames[368] = "oWaterWave";
global.__objectNames[369] = "oLiquidFilter";
global.__objectNames[370] = "oSplash";
global.__objectNames[371] = "oSmallSplash";
global.__objectNames[372] = "oLavaRise";
global.__objectNames[373] = "oMoveWater";
global.__objectNames[374] = "oWaterBackground";
global.__objectNames[375] = "oWaterFXV2";
global.__objectNames[376] = "oLBubble";
global.__objectNames[377] = "oFXTrail";
global.__objectNames[378] = "oFXAnimSpark";
global.__objectNames[379] = "oBeamTrail";
global.__objectNames[380] = "oRMissile";
global.__objectNames[381] = "oScrewAttack";
global.__objectNames[382] = "oSpeedBoost";
global.__objectNames[383] = "oMflash";
global.__objectNames[384] = "oChargeBeamSpark1";
global.__objectNames[385] = "oChargeBeamSpark2";
global.__objectNames[386] = "oSuitChangeFX";
global.__objectNames[387] = "oGravitySuitChangeFX";
global.__objectNames[388] = "oSuitChangeFX2";
global.__objectNames[389] = "oSBTrail";
global.__objectNames[390] = "oMBTrail";
global.__objectNames[391] = "oJTrail";
global.__objectNames[392] = "oSaveFX";
global.__objectNames[393] = "oSaveSparks";
global.__objectNames[394] = "oSBSpark";
global.__objectNames[395] = "oCharacterTrail";
global.__objectNames[396] = "oSpaceJumpTrail";
global.__objectNames[397] = "oScreenFlash";
global.__objectNames[398] = "oScreenFlash2";
global.__objectNames[399] = "oDebris";
global.__objectNames[400] = "oMetalDebrisBig";
global.__objectNames[401] = "oIceShard";
global.__objectNames[402] = "oSparkParticle";
global.__objectNames[403] = "oQuake";
global.__objectNames[404] = "oBigQuake";
global.__objectNames[405] = "oWaterDrop";
global.__objectNames[406] = "oSpotlight1";
global.__objectNames[407] = "oFlashLight";
global.__objectNames[408] = "oFlashLight2";
global.__objectNames[409] = "oFXFog";
global.__objectNames[410] = "oTransition";
global.__objectNames[411] = "oDeathSequence";
global.__objectNames[412] = "oWhiteParticle";
global.__objectNames[413] = "oExplosionSmoke";
global.__objectNames[414] = "oMakeScrMap";
global.__objectNames[415] = "oRecordVideo";
global.__objectNames[416] = "oScrUpperGreenShadow";
global.__objectNames[417] = "oScrUpperRedShadow";
global.__objectNames[418] = "oScrUpperBGShadow";
global.__objectNames[419] = "oScrLowerBGShadow";
global.__objectNames[420] = "oSrcHorizontalBGShadow";
global.__objectNames[421] = "oScrLeftBGShadow";
global.__objectNames[422] = "oScrRightBGShadow";
global.__objectNames[423] = "oScrVerticalBGShadow";
global.__objectNames[424] = "oPopupText";
global.__objectNames[425] = "oEMPNoise";
global.__objectNames[426] = "oFXAnimSparkItem";
global.__objectNames[427] = "oControl";
global.__objectNames[428] = "oCamera";
global.__objectNames[429] = "oEventCamera";
global.__objectNames[430] = "oEventCamera2";
global.__objectNames[431] = "oVibrate";
global.__objectNames[432] = "oTouchControls";
global.__objectNames[433] = "oObjectCamera";
global.__objectNames[434] = "oBomb";
global.__objectNames[435] = "oBombExpl";
global.__objectNames[436] = "oPBomb";
global.__objectNames[437] = "oPBombExpl";
global.__objectNames[438] = "oMissileExpl";
global.__objectNames[439] = "oBeam";
global.__objectNames[440] = "oMissile";
global.__objectNames[441] = "oBomb2";
global.__objectNames[442] = "oChargeBomb";
global.__objectNames[443] = "oMissileTrail";
global.__objectNames[444] = "oMissileFlame";
global.__objectNames[445] = "oItemBall";
global.__objectNames[446] = "oItemBall2";
global.__objectNames[447] = "oItemBall3";
global.__objectNames[448] = "oItemBall4";
global.__objectNames[449] = "oFakeItemBall";
global.__objectNames[450] = "oItemBomb";
global.__objectNames[451] = "oItemPowergrip";
global.__objectNames[452] = "oItemSpiderBall";
global.__objectNames[453] = "oItemJumpBall";
global.__objectNames[454] = "oItemHijump";
global.__objectNames[455] = "oItemVaria";
global.__objectNames[456] = "oItemSpaceJump";
global.__objectNames[457] = "oItemSpeedBooster";
global.__objectNames[458] = "oItemScrewAttack";
global.__objectNames[459] = "oItemGravity";
global.__objectNames[460] = "oItemCBeam";
global.__objectNames[461] = "oItemIBeam";
global.__objectNames[462] = "oItemWBeam";
global.__objectNames[463] = "oItemSBeam";
global.__objectNames[464] = "oItemPBeam";
global.__objectNames[465] = "oItemMissileTank";
global.__objectNames[466] = "oItemSMissileTank";
global.__objectNames[467] = "oItemPBombTank";
global.__objectNames[468] = "oItemEnergyTank";
global.__objectNames[469] = "oItem";
global.__objectNames[470] = "oGameSelMenu";
global.__objectNames[471] = "oMenuSaveSlot";
global.__objectNames[472] = "oSlotMenu1";
global.__objectNames[473] = "oSlotMenu2";
global.__objectNames[474] = "oSlotMenuErase";
global.__objectNames[475] = "oSlotMenuOverwrite";
global.__objectNames[476] = "oSlotMenuCopy";
global.__objectNames[477] = "oSlotFlash";
global.__objectNames[478] = "oPressStart";
global.__objectNames[479] = "oPressStart2";
global.__objectNames[480] = "oDrawTitleBG";
global.__objectNames[481] = "oTitleAnimation";
global.__objectNames[482] = "oTitleText1";
global.__objectNames[483] = "oTitleText2";
global.__objectNames[484] = "oGameOverMenu";
global.__objectNames[485] = "oGameOverText";
global.__objectNames[486] = "oGalleryMenu";
global.__objectNames[487] = "oGalleryOption";
global.__objectNames[488] = "oMGamma";
global.__objectNames[489] = "oMGammaTriggerProx";
global.__objectNames[490] = "oMGammaElec";
global.__objectNames[491] = "oMGammaGrab";
global.__objectNames[492] = "oMGammaArms";
global.__objectNames[493] = "oMGammaA3BTrigger";
global.__objectNames[494] = "oMGammaMutate";
global.__objectNames[495] = "oMGammaFirstTrigger";
global.__objectNames[496] = "oMAlpha";
global.__objectNames[497] = "oMAlphaShell";
global.__objectNames[498] = "oMAlphaTriggerProx";
global.__objectNames[499] = "oMAlpha2TriggerProx";
global.__objectNames[500] = "oMalpha3TriggerProx";
global.__objectNames[501] = "oMAlphaTriggerA2";
global.__objectNames[502] = "oMAlphaTriggerFirstCocoon";
global.__objectNames[503] = "oMAlphaTriggerA3A";
global.__objectNames[504] = "oMAlphaTriggerA3AL";
global.__objectNames[505] = "oMAlphaFirstTrigger";
global.__objectNames[506] = "oMZeta";
global.__objectNames[507] = "oMZetaHead";
global.__objectNames[508] = "oMZetaShield";
global.__objectNames[509] = "oMZetaBodyMask";
global.__objectNames[510] = "oMZetaSlashProj";
global.__objectNames[511] = "oMZetaSlashProj2";
global.__objectNames[512] = "oMZetaProj";
global.__objectNames[513] = "oMZetaProjFX";
global.__objectNames[514] = "oMZeta_Cocoon";
global.__objectNames[515] = "oMZetaDrool";
global.__objectNames[516] = "oMZetaFirstTrigger";
global.__objectNames[517] = "oHatchling";
global.__objectNames[518] = "oHatchlingIntro";
global.__objectNames[519] = "oMEgg1";
global.__objectNames[520] = "oMEgg2";
global.__objectNames[521] = "oMMoverLeft";
global.__objectNames[522] = "oMMoverRight";
global.__objectNames[523] = "oMMoverUp";
global.__objectNames[524] = "oMMoverDown";
global.__objectNames[525] = "oMMoverAccelH";
global.__objectNames[526] = "oMStopRight";
global.__objectNames[527] = "oMStopLeft";
global.__objectNames[528] = "oMStopUp";
global.__objectNames[529] = "oMStopDown";
global.__objectNames[530] = "oMOmega";
global.__objectNames[531] = "oMOmegaHead";
global.__objectNames[532] = "oMOmegaTail";
global.__objectNames[533] = "oMOmegaMask";
global.__objectNames[534] = "oMOmegaGrab";
global.__objectNames[535] = "oMOmegaGroundHit";
global.__objectNames[536] = "oMOmegaFlame";
global.__objectNames[537] = "oMOmegaMask2";
global.__objectNames[538] = "oMOmegaMask3";
global.__objectNames[539] = "oMOmegaMask4";
global.__objectNames[540] = "oMOmegaTailMutate";
global.__objectNames[541] = "oMOmega_Projectile";
global.__objectNames[542] = "oMonster";
global.__objectNames[543] = "oMonsterSpark";
global.__objectNames[544] = "oQueen";
global.__objectNames[545] = "oQueenHead";
global.__objectNames[546] = "oQueenLegBack";
global.__objectNames[547] = "oQueenLegFront";
global.__objectNames[548] = "oQueenFront";
global.__objectNames[549] = "oQueenProj";
global.__objectNames[550] = "oQueenHeadTop";
global.__objectNames[551] = "oQueenHeadBottom";
global.__objectNames[552] = "oQueenFireball";
global.__objectNames[553] = "oQueenGrab";
global.__objectNames[554] = "oQueenChargeParticle";
global.__objectNames[555] = "oQueenFinalGlow";
global.__objectNames[556] = "oLightRay";
global.__objectNames[557] = "oQueenBloodDrop";
global.__objectNames[558] = "oQueenFinalExplosion";
global.__objectNames[559] = "oBoss1Trigger";
global.__objectNames[560] = "oBoss1Block";
global.__objectNames[561] = "oBoss1Block2";
global.__objectNames[562] = "oBoss1Block3";
global.__objectNames[563] = "oBoss1Head";
global.__objectNames[564] = "oBoss1Beam";
global.__objectNames[565] = "oBoss1Wheel";
global.__objectNames[566] = "oBoss1FBall";
global.__objectNames[567] = "oBoss1FBExplR";
global.__objectNames[568] = "oBoss1FBExplL";
global.__objectNames[569] = "oBoss1FBall2";
global.__objectNames[570] = "oBoss1FBExpl2";
global.__objectNames[571] = "oBoss1FBall3";
global.__objectNames[572] = "oBoss1FBExpl3";
global.__objectNames[573] = "oBoss1Eyes";
global.__objectNames[574] = "oArachnusIntro";
global.__objectNames[575] = "oArachnusIntro2";
global.__objectNames[576] = "oArachnusStatue";
global.__objectNames[577] = "oArachnusStatuePiece";
global.__objectNames[578] = "oArachnus";
global.__objectNames[579] = "oArachnusFireball1";
global.__objectNames[580] = "oArachnusFBExpl";
global.__objectNames[581] = "oArachnusFBExpl3";
global.__objectNames[582] = "oArachnusFireball2";
global.__objectNames[583] = "oArachnusFireball3";
global.__objectNames[584] = "oArachnusClawProj";
global.__objectNames[585] = "oArachnusSpikes";
global.__objectNames[586] = "oJumpBallAppear";
global.__objectNames[587] = "oArachnusTrigger";
global.__objectNames[588] = "oTorizo";
global.__objectNames[589] = "oTorizo2";
global.__objectNames[590] = "oTorizoFireball";
global.__objectNames[591] = "oTorizoSlashProj";
global.__objectNames[592] = "oTorizoGrab";
global.__objectNames[593] = "oTorizoCam";
global.__objectNames[594] = "oTorizoBottom";
global.__objectNames[595] = "oTorizoCeiling";
global.__objectNames[596] = "oTorizoWall";
global.__objectNames[597] = "oTorizo2Cam";
global.__objectNames[598] = "oTorizoTrigger";
global.__objectNames[599] = "oTorizoSpikes";
global.__objectNames[600] = "oTorizoEgg";
global.__objectNames[601] = "oTorizoGhost";
global.__objectNames[602] = "oTorizoStatue";
global.__objectNames[603] = "oTorizoStatueEye";
global.__objectNames[604] = "oTorizoStatuePiece1";
global.__objectNames[605] = "oTorizoStatuePiece2";
global.__objectNames[606] = "oTorizoStatuePiece3";
global.__objectNames[607] = "oTorizoStatuePiece4";
global.__objectNames[608] = "oTorizoWings";
global.__objectNames[609] = "oTorizoJetFX";
global.__objectNames[610] = "oTesterCannon";
global.__objectNames[611] = "oTesterEye";
global.__objectNames[612] = "oTesterGlass";
global.__objectNames[613] = "oTesterIceBeam";
global.__objectNames[614] = "oTesterIceBeam2";
global.__objectNames[615] = "oTesterIceSpark";
global.__objectNames[616] = "oTesterMissile";
global.__objectNames[617] = "oTesterMissileExpl";
global.__objectNames[618] = "oTesterPlasmaBeam";
global.__objectNames[619] = "oTesterSpazerBeam";
global.__objectNames[620] = "oTesterWaveBeam";
global.__objectNames[621] = "oTester";
global.__objectNames[622] = "oTesterShield";
global.__objectNames[623] = "oTesterBossTrigger";
global.__objectNames[624] = "oTank";
global.__objectNames[625] = "oTankArm";
global.__objectNames[626] = "oTankBottom";
global.__objectNames[627] = "oTankCannon";
global.__objectNames[628] = "oTankCore";
global.__objectNames[629] = "oTankHead";
global.__objectNames[630] = "oTankProjectile";
global.__objectNames[631] = "oTankShield";
global.__objectNames[632] = "oTankBossTrigger";
global.__objectNames[633] = "oTankCam";
global.__objectNames[634] = "oEris";
global.__objectNames[635] = "oErisBody1";
global.__objectNames[636] = "oErisBody2";
global.__objectNames[637] = "oErisBody3";
global.__objectNames[638] = "oErisTail";
global.__objectNames[639] = "oErisBossTrigger";
global.__objectNames[640] = "oGenesis";
global.__objectNames[641] = "oGenesisTrigger";
global.__objectNames[642] = "oGenesisAcid";
global.__objectNames[643] = "oGenesisSlashProj";
global.__objectNames[644] = "oA8RedLightFX";
global.__objectNames[645] = "oGotoEnd";
global.__objectNames[646] = "oMusicFadeout";
global.__objectNames[647] = "oEventSolid1";
global.__objectNames[648] = "oEventSolid2";
global.__objectNames[649] = "oDrawDemoStats";
global.__objectNames[650] = "oDemoIntroSuit";
global.__objectNames[651] = "oFloorButton1";
global.__objectNames[652] = "oDemoStoryScroll";
global.__objectNames[653] = "oTextFadeIn";
global.__objectNames[654] = "oDemoPressStart1";
global.__objectNames[655] = "oDemoPressStart2";
global.__objectNames[656] = "oDemoV2";
global.__objectNames[657] = "oDemoEndSeq";
global.__objectNames[658] = "oMusicV2";
global.__objectNames[659] = "oGameIntroSeq1";
global.__objectNames[660] = "oLog";
global.__objectNames[661] = "oLogScreen";
global.__objectNames[662] = "oMapBlock";
global.__objectNames[663] = "oDrawMap";
global.__objectNames[664] = "oMapCursor";
global.__objectNames[665] = "oMapScrBG";
global.__objectNames[666] = "oMapScrBG2";
global.__objectNames[667] = "oMapScrBG3";
global.__objectNames[668] = "oDrawMap2";
global.__objectNames[669] = "oMapMarker";
global.__objectNames[670] = "oMapCamera";
global.__objectNames[671] = "oSS_Bg";
global.__objectNames[672] = "oSS_Fg";
global.__objectNames[673] = "oSS_Control";
global.__objectNames[674] = "oSubScrChange";
global.__objectNames[675] = "oPauseOption";
global.__objectNames[676] = "oNormalOption";
global.__objectNames[677] = "oNormalOptionC";
global.__objectNames[678] = "oNormalOptionR";
global.__objectNames[679] = "oOptionLR";
global.__objectNames[680] = "oOptionSlider";
global.__objectNames[681] = "oMenuLabel";
global.__objectNames[682] = "oMenuLabelR";
global.__objectNames[683] = "oPauseMenuOptions";
global.__objectNames[684] = "oOptionsMain";
global.__objectNames[685] = "oOptionsDisplay";
global.__objectNames[686] = "oOptionsSound";
global.__objectNames[687] = "oOptionsControl";
global.__objectNames[688] = "oOptionsKeyboard";
global.__objectNames[689] = "oOptionsJoypad";
global.__objectNames[690] = "oOptionsXJoypad";
global.__objectNames[691] = "oOptionsQuit";
global.__objectNames[692] = "oOptionsReload";
global.__objectNames[693] = "oOptionsBG";
global.__objectNames[694] = "oOptionsFG";
global.__objectNames[695] = "oSubScreenSuit";
global.__objectNames[696] = "oSubScreenBeam";
global.__objectNames[697] = "oSubScreenMisc";
global.__objectNames[698] = "oSubScreenBoots";
global.__objectNames[699] = "oSubScrPlayer";
global.__objectNames[700] = "oSubScrTopLayer";
global.__objectNames[701] = "oSubscreenMenu";
global.__objectNames[702] = "oLogEntry";
global.__objectNames[703] = "oLogScreenControl";
global.__objectNames[704] = "oLoadGame";
global.__objectNames[705] = "oDemoEndTrigger";
global.__objectNames[706] = "oDemoEndObj";
global.__objectNames[707] = "oItemCutscene";
global.__objectNames[708] = "oIntroController";
global.__objectNames[709] = "oIntroCutscene";
global.__objectNames[710] = "oIntroShip2";
global.__objectNames[711] = "oIntroShip1";
global.__objectNames[712] = "oIntroShip3";
global.__objectNames[713] = "oIntroClouds";
global.__objectNames[714] = "oIntroText1";
global.__objectNames[715] = "oNewGameIntro";
global.__objectNames[716] = "oScoreScreen";
global.__objectNames[717] = "oCreditsText";
global.__objectNames[718] = "oCreditsShip";
global.__objectNames[719] = "oHintTrigger";
global.__objectNames[720] = "oHTriggerDiag";
global.__objectNames[721] = "oHTriggerMorph";
global.__objectNames[722] = "oHTriggerDiag2";
global.__objectNames[723] = "oHTriggerMissiles";
global.__objectNames[724] = "oHTriggerAutoad";
global.__objectNames[725] = "oHintDoneTrigger";
global.__objectNames[726] = "oNotification";
global.__objectNames[727] = "oScanning";
global.__objectNames[728] = "oScanMonster";
global.__objectNames[729] = "oLightEngine";
global.__objectNames[730] = "oLight";
global.__objectNames[731] = "oLight64";
global.__objectNames[732] = "oFlashlight64";
global.__objectNames[733] = "oLight32";
global.__objectNames[734] = "oLight16";
global.__objectNames[735] = "oLight64Red";
global.__objectNames[736] = "oLight64Blue";
global.__objectNames[737] = "oFadeLight32";
global.__objectNames[738] = "oFadeLight64";
global.__objectNames[739] = "Rooma3c03Fix";
global.__objectNames[740] = "rm_a4a01_Fix";
global.__objectNames[741] = "Rooma4b11Fix";
global.__objectNames[742] = "oSlotMenu_gametypes";
global.__objectNames[743] = "oSlotMenu_classic";
global.__objectNames[744] = "oSlotMenu_random";
global.__objectNames[745] = "oSlotMenu_normal_only";
global.__objectNames[746] = "oSlotMenu_Fusion";
global.__objectNames[747] = "oWarpDoorBroken";
global.__objectNames[748] = "oSaveStationBroken";
global.__objectNames[749] = "oRm_a5c11lock";
global.__objectNames[750] = "godmode_GD";
global.__objectNames[751] = "hatchling_freeze";
global.__objectNames[752] = "oOptionsExtras";
global.__objectNames[753] = "oBigQuakeQueen";
global.__objectNames[754] = "oItemM_52";
global.__objectNames[755] = "oItemM_53";
global.__objectNames[756] = "oItemM_54";
global.__objectNames[757] = "oItemM_55";
global.__objectNames[758] = "oItemM_56";
global.__objectNames[759] = "oItemM_57";
global.__objectNames[760] = "oItemM_60";
global.__objectNames[761] = "oItemM_100";
global.__objectNames[762] = "oItemM_101";
global.__objectNames[763] = "oItemM_102";
global.__objectNames[764] = "oItemM_104";
global.__objectNames[765] = "oItemM_105";
global.__objectNames[766] = "oItemM_106";
global.__objectNames[767] = "oItemM_107";
global.__objectNames[768] = "oItemM_109";
global.__objectNames[769] = "oItemM_111";
global.__objectNames[770] = "oItemM_150";
global.__objectNames[771] = "oItemM_151";
global.__objectNames[772] = "oItemM_152";
global.__objectNames[773] = "oItemM_153";
global.__objectNames[774] = "oItemM_154";
global.__objectNames[775] = "oItemM_155";
global.__objectNames[776] = "oItemM_156";
global.__objectNames[777] = "oItemM_159";
global.__objectNames[778] = "oItemM_161";
global.__objectNames[779] = "oItemM_163";
global.__objectNames[780] = "oItemM_202";
global.__objectNames[781] = "oItemM_203";
global.__objectNames[782] = "oItemM_204";
global.__objectNames[783] = "oItemM_205";
global.__objectNames[784] = "oItemM_208";
global.__objectNames[785] = "oItemM_210";
global.__objectNames[786] = "oItemM_211";
global.__objectNames[787] = "oItemM_214";
global.__objectNames[788] = "oItemM_250";
global.__objectNames[789] = "oItemM_252";
global.__objectNames[790] = "oItemM_255";
global.__objectNames[791] = "oItemM_257";
global.__objectNames[792] = "oItemM_259";
global.__objectNames[793] = "oItemM_303";
global.__objectNames[794] = "oItemM_304";
global.__objectNames[795] = "oItemM_307";
global.__objectNames[796] = "oItemM_308";
global.__objectNames[797] = "oItemM_309";
global.__objectNames[798] = "oItemSM_51";
global.__objectNames[799] = "oItemSM_110";
global.__objectNames[800] = "oItemSM_162";
global.__objectNames[801] = "oItemSM_206";
global.__objectNames[802] = "oItemSM_207";
global.__objectNames[803] = "oItemSM_209";
global.__objectNames[804] = "oItemSM_215";
global.__objectNames[805] = "oItemSM_256";
global.__objectNames[806] = "oItemSM_300";
global.__objectNames[807] = "oItemSM_305";
global.__objectNames[808] = "oItemETank_50";
global.__objectNames[809] = "oItemETank_103";
global.__objectNames[810] = "oItemETank_108";
global.__objectNames[811] = "oItemETank_157";
global.__objectNames[812] = "oItemETank_158";
global.__objectNames[813] = "oItemETank_200";
global.__objectNames[814] = "oItemETank_201";
global.__objectNames[815] = "oItemETank_251";
global.__objectNames[816] = "oItemETank_254";
global.__objectNames[817] = "oItemETank_306";
global.__objectNames[818] = "oItemPB_58";
global.__objectNames[819] = "oItemPB_59";
global.__objectNames[820] = "oItemPB_112";
global.__objectNames[821] = "oItemPB_160";
global.__objectNames[822] = "oItemPB_212";
global.__objectNames[823] = "oItemPB_213";
global.__objectNames[824] = "oItemPB_253";
global.__objectNames[825] = "oItemPB_258";
global.__objectNames[826] = "oItemPB_301";
global.__objectNames[827] = "oItemPB_302";
global.__objectNames[828] = "oXPickup";
global.__objectNames[829] = "oHXPickup";
global.__objectNames[830] = "oHXPickupBig";
global.__objectNames[831] = "oMXPickup";
global.__objectNames[832] = "oSMXPickup";
global.__objectNames[833] = "oPBXPickup";
global.__objectNames[834] = "oAbsorbX";
global.__objectNames[835] = "oBlobThrowerWater";
global.__objectNames[836] = "oBlobThrowerLand";
global.__objectNames[837] = "oBlobWater";
global.__objectNames[838] = "oBlobAir";
global.__objectNames[839] = "oBlobSolid";
global.__objectNames[840] = "oBarrier2";
global.__objectNames[841] = "oMeboid2";
global.__objectNames[842] = "oSkreek2";
global.__objectNames[843] = "oSkreekSpit";
global.__objectNames[844] = "oSkreekTrigger";
global.__objectNames[845] = "oSkorpLure";
global.__objectNames[846] = "oDrivelProj";
global.__objectNames[847] = "oEndingHornoad";
global.__objectNames[848] = "oEndingCrystal";
global.__objectNames[849] = "oEndingCrystal1";
global.__objectNames[850] = "oEndingCrystal2";
global.__objectNames[851] = "oEndingCrystal3";
global.__objectNames[852] = "oEndingCrystal4";
global.__objectNames[853] = "oEndingCrystal5";
global.__objectNames[854] = "oEndingFadein";
global.__objectNames[855] = "oEndingFadeout";
global.__objectNames[856] = "oHornoadSkeleton";
global.__objectNames[857] = "oEndingMonsterEgg";
global.__objectNames[858] = "oEndingHornoadFX";
global.__objectNames[859] = "oEndingCrystalParent";
global.__objectNames[860] = "oEndingSkip";
global.__objectNames[861] = "oEndingSolid";
global.__objectNames[862] = "oErisHead";
global.__objectNames[863] = "oErisSegment";
global.__objectNames[864] = "oErisTarget1";
global.__objectNames[865] = "oErisTarget2";
global.__objectNames[866] = "oErisTarget3";
global.__objectNames[867] = "oErisTarget4";
global.__objectNames[868] = "oErisTarget5";
global.__objectNames[869] = "oErisTarget6";
global.__objectNames[870] = "oErisProjectile";
global.__objectNames[871] = "oErisPipe";
global.__objectNames[872] = "oIGT";
global.__objectNames[873] = "oGameOverBG";
global.__objectNames[874] = "oOptionsGame";
global.__objectNames[875] = "oOptionSeed";
global.__objectNames[876] = "oLogTrigger";
global.__objectNames[877] = "oBabySeptogg";
global.__objectNames[878] = "oElderSeptogg";
global.__objectNames[879] = "oCoreX";
global.__objectNames[880] = "oCoreXShell";
global.__objectNames[881] = "oElectricSparkCoreX";
global.__objectNames[882] = "oElectricSparkCoreXShort";
global.__objectNames[883] = "oOptionsMogaJoypad";
global.__objectNames[884] = "oTorizoCoreXCam";
global.__objectNames[885] = "oChozoLogMarker";
global.__objectNames[886] = "A5_Alpha_Septogg_Checker";
global.__objectNames[887] = "oCheats";
global.__objectNames[888] = "oShroom";
global.__objectNames[889] = "oShroomU";
global.__objectNames[890] = "oCordCrystal";
global.__objectNames[891] = "oShroomC";
global.__objectNames[892] = "oAreaIntro";
global.__objectNames[893] = "oA3_Missiles_Glow";
global.__objectNames[894] = "oStartupControl";


// create another array that has the correct entries
var len = array_length_1d(global.__objectDepths);
global.__objectID2Depth = [];
for( var i=0; i<len; ++i ) {
	var objID = asset_get_index( global.__objectNames[i] );
	if (objID >= 0) {
		global.__objectID2Depth[ objID ] = global.__objectDepths[i];
	} // end if
} // end for