action_inherited();
canbeX = 0;
makeActive();
setCollisionBounds(-10, -14, 14, 14);
facing = 1;
myhealth = 80;
freezehp = 30;

prevhealth = myhealth;
damage = 24;
stuntime = 5;
shell1hp = 60;
shell2hp = 40;
hpush = 6;
vpush = -3;
hitmissileexpl = 0;
hitsound = sndRobotHit3;
deathsound = sndRobotExpl;
canfreeze = 1;
platyoffset = -6;
frozenspr = sShirkFrozen;
flipx = 1;
target = 0;
state = 1;
targetx = x;
targety = y;
haccel = 0.2;
vaccel = 0.5;
alarm[0] = 1;
turning = 0;
inwater = 0;
hitemp = 1;
empspr = sShirkDisabled;

