action_inherited();
canbeX = 0;
myhealth = 200;
damage = 24;
hitbeam = 0;
hitmissile = 0;
hitmissileexpl = 0;
hitpbomb = 1;
hitbomb = 0;
hitscrewattack = 1;
hitpseudoscrew = 0;
canfreeze = 0;
hitsound = sndRobotHit4;
deathsound = sndRobotExpl;
platyoffset = -6;
frozenspr = sAutom;
flipx = 0;
target = 0;
canattack = 1;
state = 1;
calpha = 0;
alarm[0] = 1;
alarm[1] = 120;
hitemp = 1;
empspr = sAutomDisabled;

