event_inherited();
makeActive();
setCollisionBounds(-14, -14, 14, 14);
facing = 1;
myhealth = 60;
freezehp = 10;
damage = 32;
hpush = 6;
vpush = -3;
hitsound = sndEHit2;
deathsound = sndEDeath1;
platyoffset = -6;
frozenspr = sHalzynBodyFrozen;
flipx = 0;
state = 0;
shield1 = instance_create(x + 8, y - 3, oHalzynShield);
shield2 = instance_create(x - 8, y - 3, oHalzynShield);
shield2.image_xscale = -1;
shield_angle = 0;
shield_offset = 0;
time = 0;
limit_l = x - 80;
limit_r = x + 80;
glow = 0;
eyeSprite = sHalzynEye;

