action_inherited();
makeActive();
setCollisionBounds(-4, -8, 4, 0);
image_speed = 0.2;
image_index = choose(0,1);
myhealth = 14;
damage = 40;
hitsound = sndEHit1;
deathsound = sndEDeath2;
platyoffset = -1;
frozenspr = sBlobWaterFrozen;
target = 0;
canattack = 1;
state = 0;
facing = choose(-1,1);
yVelStart = random_range(-2,-1);
xVelStart = random_range(-1,1);
turnTimer = irandom_range(60,180);
driftSpeed = random_range(.3,.6);
driftMark = turnTimer/2;

